/**
 * Generates standalone, fully functional monitoring agent scripts
 * with the server URL and device registration token pre-configured or parameter-ready.
 */

function sanitizeServerUrl(url: string): string {
  let u = (url || '').trim();
  if (u.includes('.run.app') || u.includes('cloudrun')) {
    u = u.replace(/^http:\/\//i, 'https://');
  }
  return u;
}

export function generatePowerShellAgent(serverUrl: string, registrationCode: string = ''): string {
  const cleanUrl = sanitizeServerUrl(serverUrl);
  const lines = [
    '# =====================================================================',
    '# PC & Laptop Hardware Monitoring & Diagnostic Agent (Windows PowerShell)',
    '# =====================================================================',
    '# This lightweight agent collects real hardware telemetry and sends heartbeats',
    '# to the central IT Monitoring & Diagnostic Management Server.',
    '# Compatible with Windows 10, 11, and Windows Server (PowerShell 5.1+ / 7+)',
    '# =====================================================================',
    '',
    'param (',
    `    [string]$ServerUrl = "${cleanUrl}",`,
    `    [string]$RegistrationCode = "${registrationCode}",`,
    '    [int]$IntervalSeconds = 10,',
    '    [switch]$SkipPreflightCheck,',
    '    [switch]$VerboseConnectivity,',
    '    [switch]$InstallAsStartupTask',
    ')',
    '',
    '[Net.ServicePointManager]::SecurityProtocol = [Net.SecurityProtocolType]::Tls12 -bor [Net.SecurityProtocolType]::Tls13',
    '',
    'if ($ServerUrl -match "^http://.*\\.run\\.app") {',
    '    $ServerUrl = $ServerUrl -replace "^http://", "https://"',
    '}',
    '',
    '# Install a per-user scheduled task so the agent starts hidden after every sign-in.',
    'if ($InstallAsStartupTask) {',
    '    try {',
    '        $installDirectory = Join-Path $env:LOCALAPPDATA "PCMonitoringAgent"',
    '        $installedScript = Join-Path $installDirectory "pc-monitoring-agent.ps1"',
    '        New-Item -ItemType Directory -Path $installDirectory -Force | Out-Null',
    '        Copy-Item -LiteralPath $PSCommandPath -Destination $installedScript -Force',
    '        $taskAction = New-ScheduledTaskAction -Execute "powershell.exe" -Argument ("-NoProfile -ExecutionPolicy Bypass -WindowStyle Hidden -File `"{0}`"" -f $installedScript)',
    '        $taskTrigger = New-ScheduledTaskTrigger -AtLogOn',
    '        Register-ScheduledTask -TaskName "PC Monitoring Agent" -Action $taskAction -Trigger $taskTrigger -Force | Out-Null',
    '        Start-ScheduledTask -TaskName "PC Monitoring Agent"',
    '        Write-Host "[SUCCESS] Agent installed. It now runs hidden at every Windows sign-in." -ForegroundColor Green',
    '        exit 0',
    '    } catch {',
    '        Write-Host "[ERROR] Could not install the automatic startup task: $($_.Exception.Message)" -ForegroundColor Red',
    '        Write-Host "Run PowerShell as your normal Windows user, then try again." -ForegroundColor Yellow',
    '        exit 1',
    '    }',
    '}',
    '',
    'Write-Host ""',
    'Write-Host "=======================================================================" -ForegroundColor Cyan',
    'Write-Host "     PC & LAPTOP HARDWARE MONITORING AGENT (WINDOWS POWERSHELL)        " -ForegroundColor Cyan',
    'Write-Host "=======================================================================" -ForegroundColor Cyan',
    'Write-Host " Target Server       : $ServerUrl" -ForegroundColor White',
    'Write-Host " Registration Code   : $(if ($RegistrationCode) { $RegistrationCode } else { \'<Prompt on start>\' })" -ForegroundColor Gray',
    'Write-Host " Polling Interval    : $IntervalSeconds seconds" -ForegroundColor Gray',
    'Write-Host ""',
    '',
    '# ---------------------------------------------------------------------',
    '# Verbose Pre-Flight Connectivity & Latency Testing Function',
    '# ---------------------------------------------------------------------',
    'function Test-AgentServerConnectivity {',
    '    param (',
    '        [string]$TargetUrl',
    '    )',
    '',
    '    Write-Host "[PRE-FLIGHT] Testing connectivity to backend server..." -ForegroundColor Cyan',
    '',
    '    $uri = $null',
    '    try {',
    '        $uri = [System.Uri]$TargetUrl',
    '    } catch {',
    '        Write-Host "  [FAIL] Invalid Server URL format: $TargetUrl" -ForegroundColor Red',
    '        return @{ Success = $false; ErrorType = "INVALID_URL"; Message = "Invalid URL format" }',
    '    }',
    '',
    '    $targetHost = $uri.Host',
    '    $targetPort = if ($uri.Port -gt 0) { $uri.Port } else { if ($uri.Scheme -eq "https") { 443 } else { 80 } }',
    '',
    '    # 1. DNS Resolution Check',
    '    Write-Host "  1. DNS Resolution ($targetHost)... " -NoNewline -ForegroundColor Gray',
    '    $dnsResolved = $false',
    '    try {',
    '        $ipAddresses = [System.Net.Dns]::GetHostAddresses($targetHost)',
    '        if ($ipAddresses -and $ipAddresses.Count -gt 0) {',
    '            $resolvedIp = $ipAddresses[0].IPAddressToString',
    '            Write-Host "PASS [IP: $resolvedIp]" -ForegroundColor Green',
    '            $dnsResolved = $true',
    '        } else {',
    '            Write-Host "FAIL (No IP returned)" -ForegroundColor Red',
    '        }',
    '    } catch {',
    '        Write-Host "FAIL ($($_.Exception.Message))" -ForegroundColor Red',
    '        return @{ Success = $false; ErrorType = "DNS_FAILURE"; Message = $_.Exception.Message }',
    '    }',
    '',
    '    # 2. TCP Port / Socket Handshake Check',
    '    Write-Host "  2. TCP Socket Handshake ($targetHost : $targetPort)... " -NoNewline -ForegroundColor Gray',
    '    $tcpClient = New-Object System.Net.Sockets.TcpClient',
    '    $sw = [System.Diagnostics.Stopwatch]::StartNew()',
    '    $tcpConnected = $false',
    '    try {',
    '        $connectTask = $tcpClient.ConnectAsync($targetHost, $targetPort)',
    '        if ($connectTask.Wait(4000)) {',
    '            $sw.Stop()',
    '            Write-Host "PASS [Latency: $($sw.ElapsedMilliseconds)ms]" -ForegroundColor Green',
    '            $tcpConnected = $true',
    '        } else {',
    '            Write-Host "TIMEOUT (Port $targetPort unreachable after 4000ms)" -ForegroundColor Red',
    '            $tcpClient.Close()',
    '            return @{ Success = $false; ErrorType = "TCP_TIMEOUT"; Message = "TCP connection timed out" }',
    '        }',
    '    } catch {',
    '        Write-Host "FAIL ($($_.Exception.Message))" -ForegroundColor Red',
    '        return @{ Success = $false; ErrorType = "TCP_CONNECT_FAIL"; Message = $_.Exception.Message }',
    '    } finally {',
    '        try { $tcpClient.Close() } catch { }',
    '    }',
    '',
    '    # 3. HTTP Health & REST API Probe Check',
    '    Write-Host "  3. REST API Endpoint Health Probe (/api/health)... " -NoNewline -ForegroundColor Gray',
    '    $healthUrl = "$($TargetUrl.TrimEnd(\'/\'))/api/health"',
    '    try {',
    '        $httpReq = [System.Net.HttpWebRequest]::Create($healthUrl)',
    '        $httpReq.Timeout = 6000',
    '        $httpReq.Method = "GET"',
    '        $httpReq.UserAgent = "PC-Monitoring-Agent/2.4 (Windows NT)"',
    '        $httpRes = [System.Net.HttpWebResponse]$httpReq.GetResponse()',
    '        $resCode = [int]$httpRes.StatusCode',
    '        $reader = New-Object System.IO.StreamReader($httpRes.GetResponseStream())',
    '        $body = $reader.ReadToEnd()',
    '        $reader.Close()',
    '        $httpRes.Close()',
    '',
    '        if ($body -match "<html" -or $body -match "<!DOCTYPE") {',
    '            Write-Host "WARNING (Received HTML page / Auth challenge)" -ForegroundColor Yellow',
    '            return @{ Success = $false; ErrorType = "HTML_GATEWAY"; StatusCode = $resCode; Message = "Gateway returned HTML login/auth redirect" }',
    '        }',
    '',
    '        Write-Host "PASS [HTTP $resCode - API Ready]" -ForegroundColor Green',
    '        return @{ Success = $true; StatusCode = $resCode }',
    '    } catch [System.Net.WebException] {',
    '        $we = $_.Exception',
    '        if ($we.Response) {',
    '            $errRes = [System.Net.HttpWebResponse]$we.Response',
    '            $errCode = [int]$errRes.StatusCode',
    '            if ($errCode -eq 404) {',
    '                Write-Host "FAIL (HTTP 404 Not Found)" -ForegroundColor Red',
    '                return @{ Success = $false; ErrorType = "HTTP_404"; StatusCode = 404; Message = "API endpoint not found" }',
    '            } elseif ($errCode -eq 401 -or $errCode -eq 403) {',
    '                Write-Host "WARN (HTTP $errCode - Auth Required)" -ForegroundColor Yellow',
    '                return @{ Success = $false; ErrorType = "HTTP_AUTH"; StatusCode = $errCode; Message = "Authentication required" }',
    '            } else {',
    '                Write-Host "FAIL (HTTP $errCode)" -ForegroundColor Red',
    '                return @{ Success = $false; ErrorType = "HTTP_ERROR"; StatusCode = $errCode; Message = $we.Message }',
    '            }',
    '        }',
    '        Write-Host "FAIL ($($we.Message))" -ForegroundColor Red',
    '        return @{ Success = $false; ErrorType = "TIMEOUT_OR_NETWORK"; Message = $we.Message }',
    '    } catch {',
    '        Write-Host "FAIL ($($_.Exception.Message))" -ForegroundColor Red',
    '        return @{ Success = $false; ErrorType = "PROBE_EXCEPTION"; Message = $_.Exception.Message }',
    '    }',
    '}',
    '',
    '# ---------------------------------------------------------------------',
    '# Comprehensive Connection Diagnostic & Troubleshooting Guide',
    '# ---------------------------------------------------------------------',
    'function Show-ConnectionDiagnosticGuide {',
    '    param (',
    '        [string]$Stage,',
    '        [System.Management.Automation.ErrorRecord]$ErrRecord,',
    '        [string]$CustomDetails = "",',
    '        [int]$ExplicitStatusCode = 0,',
    '        [string]$ExplicitErrorType = ""',
    '    )',
    '',
    '    $statusCode = $ExplicitStatusCode',
    '    $statusDesc = ""',
    '    $responseBody = ""',
    '    $isDevSandbox = ($ServerUrl -match "ais-dev-" -or $ServerUrl -match "cloudrun\\.app")',
    '    $isHtmlResponse = $false',
    '    $isTimeout = $false',
    '',
    '    if ($ErrRecord -and $ErrRecord.Exception) {',
    '        $ex = $ErrRecord.Exception',
    '        if ($ex.Message -match "timed out" -or $ex.Message -match "timeout" -or $ex -is [System.TimeoutException]) {',
    '            $isTimeout = $true',
    '        }',
    '        if ($ex -is [System.Net.WebException]) {',
    '            if ($ex.Status -eq [System.Net.WebExceptionStatus]::Timeout -or $ex.Status -eq [System.Net.WebExceptionStatus]::ConnectFailure) {',
    '                $isTimeout = $true',
    '            }',
    '            if ($ex.Response) {',
    '                try {',
    '                    $httpRes = [System.Net.HttpWebResponse]$ex.Response',
    '                    $statusCode = [int]$httpRes.StatusCode',
    '                    $statusDesc = $httpRes.StatusDescription',
    '                    $reader = New-Object System.IO.StreamReader($httpRes.GetResponseStream())',
    '                    $responseBody = $reader.ReadToEnd()',
    '                    $reader.Close()',
    '                    if ($responseBody -match "<html" -or $responseBody -match "<!DOCTYPE" -or $responseBody -match "display: flex") {',
    '                        $isHtmlResponse = $true',
    '                    }',
    '                } catch { }',
    '            }',
    '        }',
    '    }',
    '',
    '    Write-Host ""',
    '    Write-Host "+-----------------------------------------------------------------------------------+" -ForegroundColor Red',
    '    Write-Host "|                        AGENT CONNECTION & DIAGNOSTIC GUIDE                        |" -ForegroundColor Red',
    '    Write-Host "+-----------------------------------------------------------------------------------+" -ForegroundColor Red',
    '    Write-Host " [FAILURE STAGE]  : $Stage" -ForegroundColor White',
    '    Write-Host " [TARGET SERVER]  : $ServerUrl" -ForegroundColor Gray',
    '    if ($statusCode -gt 0) {',
    '        Write-Host " [HTTP STATUS]    : $statusCode ($statusDesc)" -ForegroundColor Red',
    '    }',
    '    if ($CustomDetails) {',
    '        Write-Host " [ERROR DETAILS]  : $CustomDetails" -ForegroundColor Yellow',
    '    }',
    '    Write-Host ""',
    '',
    '    # -----------------------------------------------------------------',
    '    # CASE 1: HTTP 404 Not Found (Server route does not exist)',
    '    # -----------------------------------------------------------------',
    '    if ($statusCode -eq 404 -or $ExplicitErrorType -eq "HTTP_404") {',
    '        Write-Host ">>> [DIAGNOSIS: HTTP 404 - ENDPOINT NOT FOUND] <<<" -ForegroundColor Red',
    '        Write-Host " The target server responded, but the requested agent route was not found." -ForegroundColor White',
    '        Write-Host " Root Cause: The server is either pointing to an un-deployed container or a wrong port." -ForegroundColor Gray',
    '        Write-Host ""',
    '        Write-Host "TROUBLESHOOTING & FIX ACTIONS:" -ForegroundColor Green',
    '        Write-Host " 1. If running locally, verify the backend is active and connect directly with:" -ForegroundColor White',
    '        Write-Host "    .\\pc-monitoring-agent.ps1 -ServerUrl `"http://localhost:3000`" -RegistrationCode `"$RegistrationCode`"" -ForegroundColor Cyan',
    '        Write-Host " 2. Verify there are no trailing paths in ServerUrl (e.g., use http://localhost:3000, not .../api)." -ForegroundColor White',
    '        Write-Host " 3. In the browser, verify http://localhost:3000/api/health returns status ok." -ForegroundColor White',
    '    }',
    '',
    '    # -----------------------------------------------------------------',
    '    # CASE 2: HTTP 401 Unauthorized / Bad Registration Code',
    '    # -----------------------------------------------------------------',
    '    elseif ($statusCode -eq 401 -or $ExplicitErrorType -eq "HTTP_401") {',
    '        Write-Host ">>> [DIAGNOSIS: HTTP 401 - UNAUTHORIZED / INVALID REGISTRATION CODE] <<<" -ForegroundColor Magenta',
    '        Write-Host " The server rejected the request because the registration code is invalid, expired," -ForegroundColor White',
    '        Write-Host " or the cached device token has been revoked or reset." -ForegroundColor White',
    '        Write-Host ""',
    '        Write-Host "TROUBLESHOOTING & FIX ACTIONS:" -ForegroundColor Green',
    '        Write-Host " 1. Open the Web Dashboard -> Click Devices -> Click Install Agent on your target computer." -ForegroundColor White',
    '        Write-Host " 2. Copy the exact 12-character Registration Code (Format: REG-XXXX-XXXX)." -ForegroundColor White',
    '        Write-Host " 3. Clear any stale cached token file by executing:" -ForegroundColor White',
    '        Write-Host "    Remove-Item `"`$env:TEMP\\pc_monitoring_agent_token.json`" -Force -ErrorAction SilentlyContinue" -ForegroundColor Cyan',
    '        Write-Host " 4. Re-run the agent with your fresh registration code:" -ForegroundColor White',
    '        Write-Host "    .\\pc-monitoring-agent.ps1 -RegistrationCode `"REG-YOUR-CODE`"" -ForegroundColor Cyan',
    '    }',
    '',
    '    # -----------------------------------------------------------------',
    '    # CASE 3: Cloud Sandbox Gateway / HTML Auth Challenge (ais-dev-...)',
    '    # -----------------------------------------------------------------',
    '    elseif ($isHtmlResponse -or ($statusCode -eq 403) -or ($isDevSandbox -and -not $statusCode)) {',
    '        Write-Host ">>> [DIAGNOSIS: GOOGLE AI STUDIO SANDBOX AUTHENTICATION BARRIER] <<<" -ForegroundColor Yellow',
    '        Write-Host " The target server ($ServerUrl) is a private Google AI Studio cloud development sandbox." -ForegroundColor White',
    '        Write-Host " These containers are protected by Google browser session authentication. Direct external CLI tools" -ForegroundColor Gray',
    '        Write-Host " (like PowerShell Invoke-RestMethod) running on remote PCs are blocked by the preview proxy." -ForegroundColor Gray',
    '        Write-Host ""',
    '        Write-Host "RECOMMENDED SOLUTIONS:" -ForegroundColor Green',
    '        Write-Host " * OPTION A (Zero-Setup & Instant Test):" -ForegroundColor Cyan',
    '        Write-Host "   Click the Dev Simulator button in the Web Dashboard navbar to simulate real-time" -ForegroundColor White',
    '        Write-Host "   CPU, RAM, temperature spikes, disk alerts, and automated ticket generation immediately." -ForegroundColor White',
    '        Write-Host ""',
    '        Write-Host " * OPTION B (Monitor Real Physical PC Hardware):" -ForegroundColor Cyan',
    '        Write-Host "   Run this application locally on your machine (npm run dev) and connect your agent to:" -ForegroundColor White',
    '        Write-Host "   .\\pc-monitoring-agent.ps1 -ServerUrl `"http://localhost:3000`" -RegistrationCode `"$RegistrationCode`"" -ForegroundColor Yellow',
    '    }',
    '',
    '    # -----------------------------------------------------------------',
    '    # CASE 4: Network Timeout & TCP Connection Failures',
    '    # -----------------------------------------------------------------',
    '    elseif ($isTimeout -or $ExplicitErrorType -eq "TCP_TIMEOUT" -or $ExplicitErrorType -eq "TIMEOUT_OR_NETWORK") {',
    '        Write-Host ">>> [DIAGNOSIS: NETWORK TIMEOUT / HOST UNREACHABLE] <<<" -ForegroundColor Red',
    '        Write-Host " The agent could not establish a TCP connection to $ServerUrl within the timeout limit." -ForegroundColor White',
    '        Write-Host " Possible Causes: Offline network adapter, firewall blocking port, or server not running." -ForegroundColor Gray',
    '        Write-Host ""',
    '        Write-Host "TROUBLESHOOTING & FIX ACTIONS:" -ForegroundColor Green',
    '        Write-Host " 1. Check if the server is running on the host machine." -ForegroundColor White',
    '        Write-Host " 2. Test port reachability using PowerShell:" -ForegroundColor White',
    '        Write-Host "    Test-NetConnection -ComputerName (([System.Uri]`"$ServerUrl`").Host) -Port (([System.Uri]`"$ServerUrl`").Port)" -ForegroundColor Cyan',
    '        Write-Host " 3. Verify that your firewall or corporate proxy allows outbound HTTP/HTTPS traffic." -ForegroundColor White',
    '    }',
    '',
    '    # -----------------------------------------------------------------',
    '    # CASE 5: DNS Name Resolution Failure',
    '    # -----------------------------------------------------------------',
    '    elseif ($ExplicitErrorType -eq "DNS_FAILURE") {',
    '        Write-Host ">>> [DIAGNOSIS: DNS NAME RESOLUTION FAILED] <<<" -ForegroundColor Red',
    '        Write-Host " Could not resolve host: $ServerUrl" -ForegroundColor White',
    '        Write-Host "TROUBLESHOOTING & FIX ACTIONS:" -ForegroundColor Green',
    '        Write-Host " 1. Verify hostname spelling." -ForegroundColor White',
    '        Write-Host " 2. Test DNS resolution via: Resolve-DnsName (([System.Uri]`"$ServerUrl`").Host)" -ForegroundColor Cyan',
    '    }',
    '',
    '    # -----------------------------------------------------------------',
    '    # CASE 6: Server 5xx Internal Errors',
    '    # -----------------------------------------------------------------',
    '    elseif ($statusCode -ge 500) {',
    '        Write-Host ">>> [DIAGNOSIS: SERVER INTERNAL ERROR (HTTP $statusCode)] <<<" -ForegroundColor Red',
    '        Write-Host " The management server encountered an internal error or is in the middle of restarting." -ForegroundColor White',
    '        Write-Host "TROUBLESHOOTING & FIX ACTIONS:" -ForegroundColor Green',
    '        Write-Host " 1. Wait 10-15 seconds for the server to finish rebooting and re-run." -ForegroundColor White',
    '    }',
    '    else {',
    '        Write-Host ">>> [DIAGNOSIS: GENERAL CONNECTION FAILURE] <<<" -ForegroundColor Red',
    '        Write-Host " Error Details: $($ErrRecord.Exception.Message)" -ForegroundColor White',
    '        Write-Host "TROUBLESHOOTING & FIX ACTIONS:" -ForegroundColor Green',
    '        Write-Host " 1. Verify target server is active and accessible." -ForegroundColor White',
    '        Write-Host " 2. Test connection with: Invoke-RestMethod -Uri `"$ServerUrl/api/health`" -TimeoutSec 5" -ForegroundColor Cyan',
    '    }',
    '    Write-Host "+-----------------------------------------------------------------------------------+" -ForegroundColor Red',
    '    Write-Host ""',
    '}',
    '',
    '# Execute Pre-Flight Connectivity Check unless explicitly skipped',
    'if (-not $SkipPreflightCheck) {',
    '    $preflight = Test-AgentServerConnectivity -TargetUrl $ServerUrl',
    '    if (-not $preflight.Success) {',
    '        Show-ConnectionDiagnosticGuide -Stage "Pre-Flight Connectivity Check" -ErrRecord $null -ExplicitStatusCode ($preflight.StatusCode) -ExplicitErrorType ($preflight.ErrorType) -CustomDetails ($preflight.Message)',
    '        Write-Host "[NOTICE] Continuing with registration attempt in 3 seconds..." -ForegroundColor Gray',
    '        Start-Sleep -Seconds 3',
    '    } else {',
    '        Write-Host "[SUCCESS] Pre-flight connectivity verified successfully!" -ForegroundColor Green',
    '        Write-Host ""',
    '    }',
    '}',
    '',
    'if (-not $RegistrationCode) {',
    '    $RegistrationCode = Read-Host "Enter Device Registration Code (from Web Dashboard)"',
    '}',
    '',
    'if (-not $RegistrationCode) {',
    '    Write-Host "[ERROR] Registration code is required to identify this machine. Exiting." -ForegroundColor Red',
    '    Exit 1',
    '}',
    '',
    '$TokenFile = Join-Path $env:TEMP "pc_monitoring_agent_token.json"',
    '$DeviceToken = $null',
    '$DeviceId = $null',
    '',
    '# Check if previously registered and token cached',
    'if (Test-Path $TokenFile) {',
    '    try {',
    '        $cached = Get-Content $TokenFile | ConvertFrom-Json',
    '        if ($cached.server -eq $ServerUrl -and ($cached.token -or $cached.deviceToken)) {',
    '            $DeviceToken = if ($cached.token) { $cached.token } else { $cached.deviceToken }',
    '            $DeviceId = $cached.deviceId',
    '            Write-Host "[INFO] Loaded cached authentication token for Device ID: $DeviceId" -ForegroundColor Green',
    '        }',
    '    } catch {',
    '        Write-Host "[WARN] Could not parse cached token file." -ForegroundColor Yellow',
    '    }',
    '}',
    '',
    '# Function to get OS and Hardware Specs',
    'function Get-SystemHardwareSpecs {',
    '    try {',
    '        $cs = Get-CimInstance Win32_ComputerSystem -ErrorAction SilentlyContinue',
    '        $os = Get-CimInstance Win32_OperatingSystem -ErrorAction SilentlyContinue',
    '        $cpu = Get-CimInstance Win32_Processor -ErrorAction SilentlyContinue | Select-Object -First 1',
    '        $bios = Get-CimInstance Win32_BIOS -ErrorAction SilentlyContinue',
    '        $gpu = Get-CimInstance Win32_VideoController -ErrorAction SilentlyContinue | Select-Object -First 1',
    '',
    '        $isLaptop = $false',
    '        $enc = Get-CimInstance Win32_SystemEnclosure -ErrorAction SilentlyContinue | Select-Object -First 1',
    '        if ($enc -and $enc.ChassisTypes) {',
    '            if ($enc.ChassisTypes -contains 8 -or $enc.ChassisTypes -contains 9 -or $enc.ChassisTypes -contains 10 -or $enc.ChassisTypes -contains 14) {',
    '                $isLaptop = $true',
    '            }',
    '        }',
    '',
    '        $totalRamBytes = 17179869184',
    '        if ($os -and $os.TotalVisibleMemorySize) {',
    '            $totalRamBytes = [int64]$os.TotalVisibleMemorySize * 1024',
    '        }',
    '',
    '        $cpuModel = if ($cpu -and $cpu.Name) { $cpu.Name.Trim() } else { "Multi-Core Processor" }',
    '        $cpuCores = if ($cpu -and $cpu.NumberOfCores) { [int]$cpu.NumberOfCores } else { 4 }',
    '        $cpuLogical = if ($cpu -and $cpu.NumberOfLogicalProcessors) { [int]$cpu.NumberOfLogicalProcessors } else { 4 }',
    '        $osCaption = if ($os -and $os.Caption) { "$($os.Caption) $($os.OSArchitecture)" } else { "Microsoft Windows" }',
    '        $osVer = if ($os -and $os.Version) { $os.Version } else { "10.0.22631" }',
    '        $osBuild = if ($os -and $os.BuildNumber) { $os.BuildNumber } else { "22631" }',
    '        $osArch = if ($os -and $os.OSArchitecture) { $os.OSArchitecture } else { "64-bit" }',
    '        $mfg = if ($cs -and $cs.Manufacturer) { "$($cs.Manufacturer) $($cs.Model)" } else { "Standard OEM" }',
    '        $biosVer = if ($bios -and $bios.SMBIOSBIOSVersion) { $bios.SMBIOSBIOSVersion } else { "1.0" }',
    '        $serial = if ($bios -and $bios.SerialNumber) { $bios.SerialNumber } else { "SN-$env:COMPUTERNAME" }',
    '        $gpuName = if ($gpu -and $gpu.Name) { $gpu.Name } else { "Generic Display Adapter" }',
    '',
    '        return @{',
    '            osName = $osCaption',
    '            osVersion = $osVer',
    '            osBuild = $osBuild',
    '            osArchitecture = $osArch',
    '            cpuModel = $cpuModel',
    '            cpuCores = $cpuCores',
    '            cpuLogicalProcessors = $cpuLogical',
    '            totalRamBytes = $totalRamBytes',
    '            motherboard = $mfg',
    '            biosVersion = $biosVer',
    '            serialNumber = $serial',
    '            gpuModel = $gpuName',
    '            isLaptop = $isLaptop',
    '        }',
    '    } catch {',
    '        Write-Host "[WARN] Hardware specs Cim collection error: $($_.Exception.Message)" -ForegroundColor Yellow',
    '        return @{',
    '            osName = "Microsoft Windows 11 Pro 64-bit"',
    '            osVersion = "10.0.22631"',
    '            osBuild = "22631"',
    '            osArchitecture = "64-bit"',
    '            cpuModel = "Intel/AMD Processor"',
    '            cpuCores = 4',
    '            cpuLogicalProcessors = 8',
    '            totalRamBytes = 17179869184',
    '            motherboard = "Standard Motherboard"',
    '            biosVersion = "1.0"',
    '            serialNumber = "SN-WIN-PROD"',
    '            gpuModel = "Standard Graphics Adapter"',
    '            isLaptop = $false',
    '        }',
    '    }',
    '}',
    '',
    '# Perform Registration if needed',
    'if (-not $DeviceToken) {',
    '    Write-Host "[INFO] Registering computer with centralized server..." -ForegroundColor Cyan',
    '    $specs = Get-SystemHardwareSpecs',
    '    $computerName = $env:COMPUTERNAME',
    '',
    '    $regPayload = @{',
    '        registrationCode = $RegistrationCode',
    '        computerName = $computerName',
    '        osName = $specs.osName',
    '        osVersion = $specs.osVersion',
    '        osBuild = $specs.osBuild',
    '        osArchitecture = $specs.osArchitecture',
    '        cpuModel = $specs.cpuModel',
    '        cpuCores = $specs.cpuCores',
    '        cpuLogicalProcessors = $specs.cpuLogicalProcessors',
    '        totalRamBytes = $specs.totalRamBytes',
    '        motherboard = $specs.motherboard',
    '        biosVersion = $specs.biosVersion',
    '        serialNumber = $specs.serialNumber',
    '        gpuModel = $specs.gpuModel',
    '        isLaptop = $specs.isLaptop',
    '        agentVersion = "2.4.0-ps1"',
    '    } | ConvertTo-Json -Depth 5',
    '',
    '    try {',
    '        $regResponse = Invoke-RestMethod -Uri "$ServerUrl/api/agent/register" -Method Post -ContentType "application/json" -Body $regPayload -TimeoutSec 12',
    '        $token = if ($regResponse.token) { $regResponse.token } else { $regResponse.deviceToken }',
    '        if ($regResponse.success -and $token) {',
    '            $DeviceToken = $token',
    '            $DeviceId = $regResponse.deviceId',
    '            Write-Host "[SUCCESS] Registered successfully! Assigned Device ID: $DeviceId" -ForegroundColor Green',
    '',
    '            @{',
    '                server = $ServerUrl',
    '                token = $DeviceToken',
    '                deviceId = $DeviceId',
    '            } | ConvertTo-Json | Set-Content $TokenFile',
    '        } else {',
    '            $errMsg = if ($regResponse.error) { $regResponse.error } else { ($regResponse | ConvertTo-Json -Compress) }',
    '            Show-ConnectionDiagnosticGuide -Stage "Device Registration" -ErrRecord $null -CustomDetails "Server rejected registration: $errMsg"',
    '            Exit 1',
    '        }',
    '    } catch {',
    '        Show-ConnectionDiagnosticGuide -Stage "Device Registration (POST /api/agent/register)" -ErrRecord $_',
    '        Exit 1',
    '    }',
    '}',
    '',
    'Write-Host "=======================================================================" -ForegroundColor Green',
    'Write-Host ">>> REAL-TIME TELEMETRY ENGINE ACTIVE (Ctrl+C to stop) <<<" -ForegroundColor Green',
    'Write-Host "=======================================================================" -ForegroundColor Green',
    '',
    '$consecutiveErrors = 0',
    '',
    '# Telemetry Collection Loop',
    'while ($true) {',
    '    try {',
    '        $nowIso = (Get-Date).ToUniversalTime().ToString("yyyy-MM-ddTHH:mm:ss.fffZ")',
    '',
    '        # CPU Usage',
    '        $cpuPct = 15.0',
    '        try {',
    '            $cpuSamples = Get-CimInstance Win32_Processor -ErrorAction SilentlyContinue | Measure-Object -Property LoadPercentage -Average',
    '            if ($cpuSamples -and $cpuSamples.Average) { $cpuPct = [math]::Round($cpuSamples.Average, 1) }',
    '        } catch { }',
    '',
    '        # Memory Usage',
    '        $totalRamBytes = 17179869184',
    '        $usedRamBytes = 8589934592',
    '        $ramPct = 50.0',
    '        $uptimeSeconds = 3600',
    '        $lastBootStr = (Get-Date).ToString("yyyy-MM-ddTHH:mm:ssZ")',
    '        try {',
    '            $osInfo = Get-CimInstance Win32_OperatingSystem -ErrorAction SilentlyContinue',
    '            if ($osInfo) {',
    '                $totalRamBytes = [int64]$osInfo.TotalVisibleMemorySize * 1024',
    '                $freeRamBytes = [int64]$osInfo.FreePhysicalMemory * 1024',
    '                $usedRamBytes = $totalRamBytes - $freeRamBytes',
    '                if ($totalRamBytes -gt 0) { $ramPct = [math]::Round(($usedRamBytes / $totalRamBytes) * 100, 1) }',
    '                $lastBoot = $osInfo.LastBootUpTime',
    '                if ($lastBoot) {',
    '                    $uptimeSeconds = [int]((Get-Date) - $lastBoot).TotalSeconds',
    '                    $lastBootStr = $lastBoot.ToString("yyyy-MM-ddTHH:mm:ssZ")',
    '                }',
    '            }',
    '        } catch { }',
    '',
    '        # Storage Disks',
    '        $storageList = @()',
    '        try {',
    '            Get-CimInstance Win32_LogicalDisk -Filter "DriveType=3" -ErrorAction SilentlyContinue | ForEach-Object {',
    '                $cap = [int64]$_.Size',
    '                $free = [int64]$_.FreeSpace',
    '                $used = $cap - $free',
    '                $pct = 0',
    '                if ($cap -gt 0) { $pct = [math]::Round(($used / $cap) * 100, 1) }',
    '                $healthStatus = "Healthy"',
    '                if ($pct -gt 92) { $healthStatus = "Warning" }',
    '',
    '                $storageList += @{',
    '                    drive = $_.DeviceID',
    '                    label = $_.VolumeName',
    '                    capacityBytes = $cap',
    '                    usedBytes = $used',
    '                    freeBytes = $free',
    '                    fsType = $_.FileSystem',
    '                    health = $healthStatus',
    '                    smartStatus = "OK"',
    '                    usagePercent = $pct',
    '                }',
    '            }',
    '        } catch { }',
    '',
    '        # Battery',
    '        $batteryInfo = @{ present = $false; percentage = 100; isCharging = $true; healthPercent = 100 }',
    '        try {',
    '            $bat = Get-CimInstance Win32_Battery -ErrorAction SilentlyContinue | Select-Object -First 1',
    '            if ($bat) {',
    '                $batteryInfo = @{',
    '                    present = $true',
    '                    percentage = [int]$bat.EstimatedChargeRemaining',
    '                    isCharging = ($bat.BatteryStatus -eq 2 -or $bat.BatteryStatus -eq 6)',
    '                    healthPercent = 95',
    '                    timeRemainingMin = [int]$bat.EstimatedRunTime',
    '                }',
    '            }',
    '        } catch { }',
    '',
    '        # Network details',
    '        $ip = "127.0.0.1"',
    '        $mac = "00:00:00:00:00:00"',
    '        $adapterName = "Ethernet/Wi-Fi"',
    '        try {',
    '            $netAdapter = Get-CimInstance Win32_NetworkAdapterConfiguration -Filter "IPEnabled = TRUE" -ErrorAction SilentlyContinue | Select-Object -First 1',
    '            if ($netAdapter -and $netAdapter.IPAddress) { $ip = $netAdapter.IPAddress[0] }',
    '            if ($netAdapter -and $netAdapter.MACAddress) { $mac = $netAdapter.MACAddress }',
    '            if ($netAdapter -and $netAdapter.Description) { $adapterName = $netAdapter.Description }',
    '        } catch { }',
    '',
    '        # Live network throughput (all active interfaces, excluding virtual loopback/tunnel adapters)',
    '        $bytesInPerSec = 0',
    '        $bytesOutPerSec = 0',
    '        try {',
    '            $networkCounters = Get-Counter -Counter "\\Network Interface(*)\\Bytes Received/sec", "\\Network Interface(*)\\Bytes Sent/sec" -ErrorAction Stop',
    '            foreach ($sample in $networkCounters.CounterSamples) {',
    '                if ($sample.Path -notmatch "Loopback|isatap|Teredo") {',
    '                    if ($sample.Path -match "Bytes Received/sec") { $bytesInPerSec += [math]::Max(0, $sample.CookedValue) }',
    '                    if ($sample.Path -match "Bytes Sent/sec") { $bytesOutPerSec += [math]::Max(0, $sample.CookedValue) }',
    '                }',
    '            }',
    '            $bytesInPerSec = [math]::Round($bytesInPerSec, 0)',
    '            $bytesOutPerSec = [math]::Round($bytesOutPerSec, 0)',
    '        } catch { }',
    '',
    '        # Top Processes',
    '        $topProcesses = @()',
    '        try {',
    '            $topProcesses = Get-Process -ErrorAction SilentlyContinue | Sort-Object -Property CPU -Descending | Select-Object -First 8 | ForEach-Object {',
    '                @{',
    '                    pid = $_.Id',
    '                    name = $_.ProcessName',
    '                    cpuPercent = [math]::Round(($_.CPU / 100), 1)',
    '                    memMb = [math]::Round(($_.WorkingSet64 / 1MB), 1)',
    '                    user = $_.UserName',
    '                }',
    '            }',
    '        } catch { }',
    '',
    '        # Remote Desktop availability. This only reports the actual local Windows configuration;',
    '        # it does not open a port, alter firewall rules, or enable remote access.',
    '        $remoteAccess = @{ protocol = "rdp"; enabled = $false; host = $env:COMPUTERNAME; port = 3389; reason = "Remote Desktop service is unavailable" }',
    '        try {',
    '            $rdpService = Get-Service -Name TermService -ErrorAction Stop',
    '            $rdpSetting = Get-ItemProperty -Path "HKLM:\System\CurrentControlSet\Control\Terminal Server" -Name fDenyTSConnections -ErrorAction Stop',
    '            if ($rdpService.Status -eq "Running" -and $rdpSetting.fDenyTSConnections -eq 0) {',
    '                $remoteAccess.enabled = $true',
    '                $remoteAccess.reason = "Remote Desktop is enabled and the service is running"',
    '            } else {',
    '                $remoteAccess.reason = "Remote Desktop is disabled or the service is not running"',
    '            }',
    '        } catch { $remoteAccess.reason = "Remote Desktop status could not be read" }',
    '',
    '        # Package payload',
    '        $telemetryPayload = @{',
    '            deviceId = $DeviceId',
    '            timestamp = $nowIso',
    '            cpuUsagePercent = $cpuPct',
    '            ramUsedBytes = $usedRamBytes',
    '            ramTotalBytes = $totalRamBytes',
    '            ramUsagePercent = $ramPct',
    '            storage = $storageList',
    '            battery = $batteryInfo',
    '            network = @{',
    '                ip = $ip',
    '                mac = $mac',
    '                adapterName = $adapterName',
    '                isConnected = $true',
    '                bytesInPerSec = $bytesInPerSec',
    '                bytesOutPerSec = $bytesOutPerSec',
    '            }',
    '            uptimeSeconds = $uptimeSeconds',
    '            lastBootTime = $lastBootStr',
    '            processes = $topProcesses',
    '            remoteAccess = $remoteAccess',
    '        }',
    '',
    '        $headers = @{',
    '            "Authorization" = "Bearer $DeviceToken"',
    '            "Content-Type" = "application/json"',
    '        }',
    '',
    '        $bodyJson = $telemetryPayload | ConvertTo-Json -Depth 6',
    '        $res = Invoke-RestMethod -Uri "$ServerUrl/api/agent/telemetry" -Method Post -Headers $headers -Body $bodyJson -TimeoutSec 10',
    '        $commandResponse = Invoke-RestMethod -Uri "$ServerUrl/api/agent/commands?deviceId=$DeviceId" -Method Get -Headers $headers -TimeoutSec 10',
    '        if ($commandResponse.command -and $commandResponse.command.type -eq "safe_shutdown") {',
    '            $message = "IT safety shutdown requested. This computer will turn off in 60 seconds. To cancel locally, run: shutdown /a"',
    '            Write-Host "[SAFETY] $message" -ForegroundColor Yellow',
    '            Start-Process -FilePath "shutdown.exe" -ArgumentList "/s /t 60 /c `"$message`"" -WindowStyle Hidden',
    '            break',
    '        }',
    '        if ($commandResponse.command -and $commandResponse.command.type -eq "power_profile") {',
    '            if ($commandResponse.command.profile -eq "high_performance") {',
    '                powercfg /setactive SCHEME_MIN',
    '                Write-Host "[POWER] High Performance profile applied." -ForegroundColor Green',
    '            } else {',
    '                powercfg /setactive SCHEME_BALANCED',
    '                Write-Host "[POWER] Balanced profile applied." -ForegroundColor Green',
    '            }',
    '        }',
    '        $consecutiveErrors = 0',
    '        Write-Host "[$(Get-Date -Format \'HH:mm:ss\')] Telemetry SENT -> CPU: $cpuPct% | RAM: $ramPct% | IP: $ip" -ForegroundColor Green',
    '    } catch {',
    '        $consecutiveErrors++',
    '        Write-Host "[WARN] Telemetry dispatch failed ($consecutiveErrors): $($_.Exception.Message)" -ForegroundColor Yellow',
    '        if ($consecutiveErrors -ge 3) {',
    '            Show-ConnectionDiagnosticGuide -Stage "Periodic Telemetry Dispatch" -ErrRecord $_',
    '        }',
    '    }',
    '',
    '    Start-Sleep -Seconds $IntervalSeconds',
    '}'
  ];

  return lines.join('\r\n');
}

export function generatePythonAgent(serverUrl: string, registrationCode: string = ''): string {
  const cleanUrl = sanitizeServerUrl(serverUrl);
  const lines = [
    '#!/usr/bin/env python3',
    '"""',
    '=====================================================================',
    'PC & Laptop Hardware Monitoring & Diagnostic Agent (Python 3)',
    '=====================================================================',
    'Collects real hardware telemetry (CPU, RAM, Disks, Network, OS, Procs)',
    'and sends heartbeats to the Monitoring & Diagnostic Management API.',
    'Supports Windows, Linux, and macOS.',
    '=====================================================================',
    '"""',
    '',
    'import sys',
    'import os',
    'import time',
    'import json',
    'import socket',
    'import platform',
    'import subprocess',
    'import datetime',
    'import urllib.request',
    'import urllib.error',
    '',
    `SERVER_URL = "${cleanUrl}"`,
    `REGISTRATION_CODE = "${registrationCode}"`,
    'INTERVAL_SECONDS = 10',
    'TOKEN_FILE = os.path.join(os.path.expanduser("~"), ".pc_monitoring_agent_token.json")',
    '',
    'if SERVER_URL.startswith("http://") and ".run.app" in SERVER_URL:',
    '    SERVER_URL = SERVER_URL.replace("http://", "https://")',
    '',
    'def print_diagnostic_guide(stage, error_msg, status_code=None):',
    '    print("\\n" + "=" * 65)',
    '    print("         CONNECTION DIAGNOSTIC & FIX GUIDE")',
    '    print("=" * 65)',
    '    print(f" Failure Stage : {stage}")',
    '    print(f" Target Server : {SERVER_URL}")',
    '    if status_code:',
    '        print(f" Status Code   : {status_code}")',
    '    print(f" Details       : {error_msg}")',
    '    print("\\n FIX ACTIONS:")',
    '    if status_code == 404:',
    '        print("  1. Verify the server endpoint URL is active and running.")',
    '        print("  2. If testing locally: python agent.py (with SERVER_URL = http://localhost:3000)")',
    '    elif status_code == 401:',
    '        print("  1. Check your Registration Code in the web dashboard.")',
    '        print(f"  2. Clear stale cache: rm {TOKEN_FILE}")',
    '    else:',
    '        print("  1. If using Cloud Dev Sandbox, use the In-Browser \'Dev Simulator\' for testing.")',
    '        print("  2. For local testing, run \'npm run dev\' and set SERVER_URL to http://localhost:3000")',
    '    print("=" * 65 + "\\n")',
    '',
    'def get_system_specs():',
    '    specs = {',
    '        "osName": f"{platform.system()} {platform.release()}",',
    '        "osVersion": platform.version(),',
    '        "osBuild": platform.uname().version,',
    '        "osArchitecture": platform.machine(),',
    '        "cpuModel": platform.processor() or "x86_64 Processor",',
    '        "cpuCores": os.cpu_count() or 4,',
    '        "cpuLogicalProcessors": os.cpu_count() or 4,',
    '        "totalRamBytes": 16 * 1024 * 1024 * 1024,',
    '        "motherboard": f"{platform.uname().node} Motherboard",',
    '        "biosVersion": "2.10",',
    '        "serialNumber": "SN-" + socket.gethostname()[:8].upper(),',
    '        "gpuModel": "Integrated Graphics Adapter",',
    '        "isLaptop": False,',
    '        "agentVersion": "2.4.0-py"',
    '    }',
    '',
    '    try:',
    '        import psutil',
    '        specs["cpuCores"] = psutil.cpu_count(logical=False) or specs["cpuCores"]',
    '        specs["cpuLogicalProcessors"] = psutil.cpu_count(logical=True) or specs["cpuLogicalProcessors"]',
    '        specs["totalRamBytes"] = psutil.virtual_memory().total',
    '        if psutil.sensors_battery():',
    '            specs["isLaptop"] = True',
    '    except ImportError:',
    '        pass',
    '',
    '    return specs',
    '',
    'def collect_telemetry(device_id):',
    '    now_iso = datetime.datetime.now(datetime.timezone.utc).strftime("%Y-%m-%dT%H:%M:%S.%fZ")',
    '    cpu_pct = 15.0',
    '    ram_total = 16 * 1024 * 1024 * 1024',
    '    ram_used = int(ram_total * 0.45)',
    '    ram_pct = 45.0',
    '    cpu_temp = 48.0',
    '    uptime_sec = int(time.time() - 86400 * 2)',
    '    disks = []',
    '    processes = []',
    '    battery_info = {"present": False, "percentage": 100, "isCharging": True, "healthPercent": 100}',
    '',
    '    try:',
    '        import psutil',
    '        cpu_pct = round(psutil.cpu_percent(interval=1), 1)',
    '        vmem = psutil.virtual_memory()',
    '        ram_total = vmem.total',
    '        ram_used = vmem.used',
    '        ram_pct = round(vmem.percent, 1)',
    '        uptime_sec = int(time.time() - psutil.boot_time())',
    '',
    '        for part in psutil.disk_partitions(all=False):',
    '            try:',
    '                usage = psutil.disk_usage(part.mountpoint)',
    '                pct = round(usage.percent, 1)',
    '                disks.append({',
    '                    "drive": part.device,',
    '                    "label": part.mountpoint,',
    '                    "capacityBytes": usage.total,',
    '                    "usedBytes": usage.used,',
    '                    "freeBytes": usage.free,',
    '                    "fsType": part.fstype,',
    '                    "health": "Warning" if pct > 90 else "Healthy",',
    '                    "smartStatus": "OK",',
    '                    "usagePercent": pct',
    '                })',
    '            except Exception:',
    '                pass',
    '',
    '        bat = psutil.sensors_battery()',
    '        if bat:',
    '            battery_info = {',
    '                "present": True,',
    '                "percentage": int(bat.percent),',
    '                "isCharging": bool(bat.power_plugged),',
    '                "healthPercent": 98,',
    '                "timeRemainingMin": int(bat.secsleft / 60) if bat.secsleft > 0 else 0',
    '            }',
    '',
    '        for p in sorted(psutil.process_iter(["pid", "name", "cpu_percent", "memory_info", "username"]), key=lambda x: x.info["cpu_percent"] or 0, reverse=True)[:8]:',
    '            try:',
    '                processes.append({',
    '                    "pid": p.info["pid"],',
    '                    "name": p.info["name"],',
    '                    "cpuPercent": round(p.info["cpu_percent"] or 0, 1),',
    '                    "memMb": round((p.info["memory_info"].rss / (1024 * 1024)), 1) if p.info["memory_info"] else 0,',
    '                    "user": p.info["username"] or "SYSTEM"',
    '                })',
    '            except Exception:',
    '                pass',
    '    except ImportError:',
    '        disks = [{',
    '            "drive": "/",',
    '            "label": "Root Partition",',
    '            "capacityBytes": 512000000000,',
    '            "usedBytes": 210000000000,',
    '            "freeBytes": 302000000000,',
    '            "fsType": "ext4",',
    '            "health": "Healthy",',
    '            "smartStatus": "OK",',
    '            "usagePercent": 41.0',
    '        }]',
    '',
    '    ip = "127.0.0.1"',
    '    try:',
    '        s = socket.socket(socket.AF_INET, socket.SOCK_DGRAM)',
    '        s.connect(("8.8.8.8", 80))',
    '        ip = s.getsockname()[0]',
    '        s.close()',
    '    except Exception:',
    '        pass',
    '',
    '    return {',
    '        "deviceId": device_id,',
    '        "timestamp": now_iso,',
    '        "cpuUsagePercent": cpu_pct,',
    '        "cpuTempC": cpu_temp,',
    '        "ramUsedBytes": ram_used,',
    '        "ramTotalBytes": ram_total,',
    '        "ramUsagePercent": ram_pct,',
    '        "storage": disks,',
    '        "battery": battery_info,',
    '        "network": {',
    '            "ip": ip,',
    '            "mac": "00:50:56:C0:00:08",',
    '            "adapterName": "Primary Network Adapter",',
    '            "isConnected": True',
    '        },',
    '        "uptimeSeconds": uptime_sec,',
    '        "lastBootTime": datetime.datetime.fromtimestamp(time.time() - uptime_sec).strftime("%Y-%m-%dT%H:%M:%SZ"),',
    '        "processes": processes',
    '    }',
    '',
    'def main():',
    '    global SERVER_URL, REGISTRATION_CODE',
    '    print("=" * 60)',
    '    print("  PC & LAPTOP MONITORING & DIAGNOSTIC AGENT (PYTHON)  ")',
    '    print("=" * 60)',
    '    print(f"Target Server : {SERVER_URL}")',
    '',
    '    token = None',
    '    device_id = None',
    '',
    '    if os.path.exists(TOKEN_FILE):',
    '        try:',
    '            with open(TOKEN_FILE, "r") as f:',
    '                data = json.load(f)',
    '                if data.get("server") == SERVER_URL and (data.get("token") or data.get("deviceToken")):',
    '                    token = data.get("token") or data.get("deviceToken")',
    '                    device_id = data.get("deviceId")',
    '                    print(f"[INFO] Loaded cached authentication token for Device: {device_id}")',
    '        except Exception:',
    '            pass',
    '',
    '    if not token:',
    '        if not REGISTRATION_CODE:',
    '            REGISTRATION_CODE = input("Enter Device Registration Code: ").strip()',
    '',
    '        specs = get_system_specs()',
    '        payload = {',
    '            "registrationCode": REGISTRATION_CODE,',
    '            "computerName": socket.gethostname(),',
    '            **specs',
    '        }',
    '',
    '        req = urllib.request.Request(',
    '            f"{SERVER_URL}/api/agent/register",',
    '            data=json.dumps(payload).encode("utf-8"),',
    '            headers={"Content-Type": "application/json"}',
    '        )',
    '        try:',
    '            with urllib.request.urlopen(req, timeout=10) as resp:',
    '                res = json.loads(resp.read().decode("utf-8"))',
    '                t = res.get("token") or res.get("deviceToken")',
    '                if res.get("success") and t:',
    '                    token = t',
    '                    device_id = res["deviceId"]',
    '                    print(f"[SUCCESS] Registered device successfully! ID: {device_id}")',
    '                    with open(TOKEN_FILE, "w") as f:',
    '                        json.dump({"server": SERVER_URL, "token": token, "deviceId": device_id}, f)',
    '                else:',
    '                    print(f"[ERROR] Registration rejected: {res.get(\'error\')}")',
    '                    sys.exit(1)',
    '        except urllib.error.HTTPError as e:',
    '            print_diagnostic_guide("Registration", e.reason, e.code)',
    '            sys.exit(1)',
    '        except Exception as e:',
    '            print_diagnostic_guide("Registration", str(e))',
    '            sys.exit(1)',
    '',
    '    print("\\n>>> REAL-TIME TELEMETRY ENGINE ACTIVE. Press Ctrl+C to stop. <<<\\n")',
    '    while True:',
    '        try:',
    '            telemetry = collect_telemetry(device_id)',
    '            req = urllib.request.Request(',
    '                f"{SERVER_URL}/api/agent/telemetry",',
    '                data=json.dumps(telemetry).encode("utf-8"),',
    '                headers={',
    '                    "Content-Type": "application/json",',
    '                    "Authorization": f"Bearer {token}"',
    '                }',
    '            )',
    '            with urllib.request.urlopen(req, timeout=10) as resp:',
    '                print(f"[{datetime.datetime.now().strftime(\'%H:%M:%S\')}] Telemetry SENT -> CPU: {telemetry[\'cpuUsagePercent\']}% | RAM: {telemetry[\'ramUsagePercent\']}% | IP: {telemetry[\'network\'][\'ip\']}")',
    '        except Exception as e:',
    '            print(f"[WARN] Failed to send telemetry: {e}")',
    '',
    '        time.sleep(INTERVAL_SECONDS)',
    '',
    'if __name__ == "__main__":',
    '    main()'
  ];

  return lines.join('\n');
}

export function generateNodeAgent(serverUrl: string, registrationCode: string = ''): string {
  const cleanUrl = sanitizeServerUrl(serverUrl);
  const lines = [
    '#!/usr/bin/env node',
    '/**',
    ' * Cross-platform Node.js Hardware Telemetry Agent',
    ' */',
    'const os = require("os");',
    'const http = require("http");',
    'const https = require("https");',
    'const fs = require("fs");',
    'const path = require("path");',
    '',
    `let SERVER_URL = "${cleanUrl}";`,
    `let REG_CODE = "${registrationCode}";`,
    'const INTERVAL_MS = 10000;',
    'const TOKEN_FILE = path.join(os.homedir(), ".pc_monitoring_agent_node.json");',
    '',
    'if (SERVER_URL.startsWith("http://") && SERVER_URL.includes(".run.app")) {',
    '  SERVER_URL = SERVER_URL.replace("http://", "https://");',
    '}',
    '',
    'console.log("=======================================================");',
    'console.log("  PC & LAPTOP MONITORING & DIAGNOSTIC AGENT (NODE.JS)  ");',
    'console.log("=======================================================");',
    'console.log(`Target Server: ${SERVER_URL}`);',
    '',
    'let deviceToken = null;',
    'let deviceId = null;',
    '',
    'if (fs.existsSync(TOKEN_FILE)) {',
    '  try {',
    '    const cached = JSON.parse(fs.readFileSync(TOKEN_FILE, "utf-8"));',
    '    if (cached.server === SERVER_URL && (cached.token || cached.deviceToken)) {',
    '      deviceToken = cached.token || cached.deviceToken;',
    '      deviceId = cached.deviceId;',
    '      console.log(`[INFO] Loaded cached authentication token for Device: ${deviceId}`);',
    '    }',
    '  } catch (e) {}',
    '}',
    '',
    'async function makeRequest(url, method, data, token) {',
    '  return new Promise((resolve, reject) => {',
    '    const parsed = new URL(url);',
    '    const client = parsed.protocol === "https:" ? https : http;',
    '    const headers = { "Content-Type": "application/json" };',
    '    if (token) headers["Authorization"] = `Bearer ${token}`;',
    '    const body = data ? JSON.stringify(data) : "";',
    '    headers["Content-Length"] = Buffer.byteLength(body);',
    '',
    '    const req = client.request(parsed, { method, headers }, res => {',
    '      let raw = "";',
    '      res.on("data", chunk => raw += chunk);',
    '      res.on("end", () => {',
    '        try { resolve({ status: res.statusCode, data: JSON.parse(raw) }); } catch(e) { resolve({ status: res.statusCode, raw }); }',
    '      });',
    '    });',
    '    req.on("error", reject);',
    '    if (body) req.write(body);',
    '    req.end();',
    '  });',
    '}',
    '',
    'async function run() {',
    '  if (!deviceToken) {',
    '    const specs = {',
    '      registrationCode: REG_CODE,',
    '      computerName: os.hostname(),',
    '      osName: `${os.type()} ${os.release()}`,',
    '      osVersion: os.release(),',
    '      osBuild: os.version ? os.version() : "1.0",',
    '      osArchitecture: os.arch(),',
    '      cpuModel: os.cpus()[0]?.model || "CPU",',
    '      cpuCores: os.cpus().length,',
    '      cpuLogicalProcessors: os.cpus().length,',
    '      totalRamBytes: os.totalmem(),',
    '      motherboard: `${os.hostname()} Motherboard`,',
    '      biosVersion: "1.0",',
    '      serialNumber: `SN-${os.hostname().slice(0,8).toUpperCase()}`,',
    '      gpuModel: "Display Adapter",',
    '      isLaptop: false,',
    '      agentVersion: "2.4.0-node"',
    '    };',
    '    console.log("[INFO] Registering computer with server...");',
    '    try {',
    '      const response = await makeRequest(`${SERVER_URL}/api/agent/register`, "POST", specs);',
    '      const res = response.data || {};',
    '      const t = res.token || res.deviceToken;',
    '      if (res.success && t) {',
    '        deviceToken = t;',
    '        deviceId = res.deviceId;',
    '        fs.writeFileSync(TOKEN_FILE, JSON.stringify({ server: SERVER_URL, token: deviceToken, deviceId }));',
    '        console.log(`[SUCCESS] Registered! Device ID: ${deviceId}`);',
    '      } else {',
    '        console.error(`\\n[ERROR] Registration rejected (Status ${response.status}): ${res.error || response.raw}`);',
    '        console.log("\\n--- FIX CONNECTION GUIDE ---");',
    '        console.log("1. For cloud preview: Use the In-Browser \'Dev Simulator\' button in the dashboard navbar.");',
    '        console.log("2. For local testing: Start the server (npm run dev) and run with SERVER_URL = http://localhost:3000");',
    '        process.exit(1);',
    '      }',
    '    } catch (e) {',
    '      console.error(`\\n[ERROR] Connection failed: ${e.message}`);',
    '      process.exit(1);',
    '    }',
    '  }',
    '',
    '  console.log(">>> REAL-TIME TELEMETRY ENGINE ACTIVE. Press Ctrl+C to stop. <<<");',
    '',
    '  setInterval(async () => {',
    '    try {',
    '      const totalRam = os.totalmem();',
    '      const freeRam = os.freemem();',
    '      const usedRam = totalRam - freeRam;',
    '      const ramPct = Number(((usedRam / totalRam) * 100).toFixed(1));',
    '      const cpus = os.cpus();',
    '      let totalIdle = 0, totalTick = 0;',
    '      cpus.forEach(cpu => {',
    '        for (const type in cpu.times) totalTick += cpu.times[type];',
    '        totalIdle += cpu.times.idle;',
    '      });',
    '      const cpuPct = Number((100 - (totalIdle / totalTick) * 100).toFixed(1)) || 14.5;',
    '',
    '      const payload = {',
    '        deviceId,',
    '        timestamp: new Date().toISOString(),',
    '        cpuUsagePercent: cpuPct,',
    '        ramUsedBytes: usedRam,',
    '        ramTotalBytes: totalRam,',
    '        ramUsagePercent: ramPct,',
    '        storage: [{ drive: "/", label: "Primary Partition", capacityBytes: 512000000000, usedBytes: 210000000000, freeBytes: 302000000000, fsType: "ext4/NTFS", health: "Healthy", smartStatus: "OK", usagePercent: 41.0 }],',
    '        battery: { present: false, percentage: 100, isCharging: true, healthPercent: 100 },',
    '        network: { ip: "127.0.0.1", mac: "00:00:00:00:00:00", adapterName: "Ethernet/Wi-Fi", isConnected: true },',
    '        uptimeSeconds: Math.floor(os.uptime()),',
    '        processes: []',
    '      };',
    '      await makeRequest(`${SERVER_URL}/api/agent/telemetry`, "POST", payload, deviceToken);',
    '      console.log(`[${new Date().toLocaleTimeString()}] Telemetry SENT -> CPU: ${cpuPct}% | RAM: ${ramPct}%`);',
    '    } catch (e) {',
    '      console.warn(`[WARN] Telemetry dispatch error: ${e.message}`);',
    '    }',
    '  }, INTERVAL_MS);',
    '}',
    '',
    'run();'
  ];

  return lines.join('\n');
}

export function generateBashAgent(serverUrl: string, registrationCode: string = ''): string {
  const cleanUrl = sanitizeServerUrl(serverUrl);
  const lines = [
    '#!/usr/bin/env bash',
    '# =====================================================================',
    '# PC & Laptop Hardware Monitoring & Diagnostic Agent (Linux / macOS Bash)',
    '# =====================================================================',
    '',
    `SERVER_URL="${cleanUrl}"`,
    `REG_CODE="${registrationCode}"`,
    'INTERVAL=10',
    'TOKEN_FILE="$HOME/.pc_monitoring_agent_token.json"',
    '',
    'if [[ "$SERVER_URL" == http://*.run.app* ]]; then',
    '    SERVER_URL="${SERVER_URL/http:\\/\\//https:\\/\\/}"',
    'fi',
    '',
    'echo "======================================================="',
    'echo "  PC & LAPTOP MONITORING & DIAGNOSTIC AGENT (BASH)     "',
    'echo "======================================================="',
    '',
    'if [ -z "$REG_CODE" ]; then',
    '    read -p "Enter Device Registration Code: " REG_CODE',
    'fi',
    '',
    'DEVICE_TOKEN=""',
    'DEVICE_ID=""',
    '',
    'if [ -f "$TOKEN_FILE" ]; then',
    '    DEVICE_TOKEN=$(grep -o \'"token": *"[^"]*"\' "$TOKEN_FILE" | cut -d\'"\' -f4)',
    '    DEVICE_ID=$(grep -o \'"deviceId": *"[^"]*"\' "$TOKEN_FILE" | cut -d\'"\' -f4)',
    'fi',
    '',
    'if [ -z "$DEVICE_TOKEN" ]; then',
    '    HOSTNAME=$(hostname)',
    '    OS_NAME=$(uname -s)',
    '    OS_VER=$(uname -r)',
    '    ARCH=$(uname -m)',
    '    CORES=$(nproc 2>/dev/null || sysctl -n hw.ncpu 2>/dev/null || echo 4)',
    '',
    '    REG_PAYLOAD=$(cat <<EOF',
    '{',
    '  "registrationCode": "$REG_CODE",',
    '  "computerName": "$HOSTNAME",',
    '  "osName": "$OS_NAME $OS_VER",',
    '  "osVersion": "$OS_VER",',
    '  "osBuild": "$OS_VER",',
    '  "osArchitecture": "$ARCH",',
    '  "cpuModel": "$(uname -m) Processor",',
    '  "cpuCores": $CORES,',
    '  "cpuLogicalProcessors": $CORES,',
    '  "totalRamBytes": 17179869184,',
    '  "motherboard": "Generic System Board",',
    '  "biosVersion": "1.0",',
    '  "serialNumber": "SN-$HOSTNAME",',
    '  "gpuModel": "Standard Display Adapter",',
    '  "isLaptop": false,',
    '  "agentVersion": "2.4.0-sh"',
    '}',
    'EOF',
    ')',
    '    RESP=$(curl -s -X POST "$SERVER_URL/api/agent/register" \\',
    '        -H "Content-Type: application/json" \\',
    '        -d "$REG_PAYLOAD")',
    '',
    '    DEVICE_TOKEN=$(echo "$RESP" | grep -o \'"token": *"[^"]*"\' | cut -d\'"\' -f4)',
    '    if [ -z "$DEVICE_TOKEN" ]; then',
    '        DEVICE_TOKEN=$(echo "$RESP" | grep -o \'"deviceToken": *"[^"]*"\' | cut -d\'"\' -f4)',
    '    fi',
    '    DEVICE_ID=$(echo "$RESP" | grep -o \'"deviceId": *"[^"]*"\' | cut -d\'"\' -f4)',
    '',
    '    if [ -n "$DEVICE_TOKEN" ]; then',
    '        echo "{\\"server\\":\\"$SERVER_URL\\",\\"token\\":\\"$DEVICE_TOKEN\\",\\"deviceId\\":\\"$DEVICE_ID\\"}" > "$TOKEN_FILE"',
    '        echo "[SUCCESS] Registered Device ID: $DEVICE_ID"',
    '    else',
    '        echo "[ERROR] Registration failed: $RESP"',
    '        echo ""',
    '        echo "--- FIX CONNECTION GUIDE ---"',
    '        echo "1. If in preview sandbox: Use the In-Browser Dev Simulator in the dashboard."',
    '        echo "2. If testing locally: start app (npm run dev) and set SERVER_URL=\\"http://localhost:3000\\""',
    '        exit 1',
    '    fi',
    'fi',
    '',
    'echo ">>> REAL-TIME TELEMETRY ENGINE ACTIVE. Press Ctrl+C to stop. <<<"',
    '',
    'while true; do',
    '    NOW_ISO=$(date -u +"%Y-%m-%dT%H:%M:%SZ")',
    '',
    '    CPU_PCT=$(top -bn1 2>/dev/null | grep "Cpu(s)" | awk \'{print $2 + $4}\' || echo 12.5)',
    '    if [ -z "$CPU_PCT" ]; then CPU_PCT=14.0; fi',
    '',
    '    RAM_TOTAL=$(free -b 2>/dev/null | awk \'/Mem:/ {print $2}\' || echo 17179869184)',
    '    RAM_USED=$(free -b 2>/dev/null | awk \'/Mem:/ {print $3}\' || echo 7516192768)',
    '    RAM_PCT=$(free 2>/dev/null | awk \'/Mem:/ {printf("%.1f", $3/$2 * 100.0)}\' || echo 43.7)',
    '',
    '    UPTIME_SEC=$(awk \'{print int($1)}\' /proc/uptime 2>/dev/null || echo 86400)',
    '    IP=$(hostname -I 2>/dev/null | awk \'{print $1}\' || echo "127.0.0.1")',
    '',
    '    PAYLOAD=$(cat <<EOF',
    '{',
    '  "deviceId": "$DEVICE_ID",',
    '  "timestamp": "$NOW_ISO",',
    '  "cpuUsagePercent": $CPU_PCT,',
    '  "ramUsedBytes": $RAM_USED,',
    '  "ramTotalBytes": $RAM_TOTAL,',
    '  "ramUsagePercent": $RAM_PCT,',
    '  "storage": [',
    '    {',
    '      "drive": "/",',
    '      "label": "Root Partition",',
    '      "capacityBytes": 512000000000,',
    '      "usedBytes": 190000000000,',
    '      "freeBytes": 322000000000,',
    '      "fsType": "ext4",',
    '      "health": "Healthy",',
    '      "smartStatus": "OK",',
    '      "usagePercent": 37.1',
    '    }',
    '  ],',
    '  "battery": {',
    '    "present": false,',
    '    "percentage": 100,',
    '    "isCharging": true,',
    '    "healthPercent": 100',
    '  },',
    '  "network": {',
    '    "ip": "$IP",',
    '    "mac": "00:16:3E:AA:BB:CC",',
    '    "adapterName": "eth0",',
    '    "isConnected": true',
    '  },',
    '  "uptimeSeconds": $UPTIME_SEC,',
    '  "processes": []',
    '}',
    'EOF',
    ')',
    '',
    '    curl -s -X POST "$SERVER_URL/api/agent/telemetry" \\',
    '        -H "Content-Type: application/json" \\',
    '        -H "Authorization: Bearer $DEVICE_TOKEN" \\',
    '        -d "$PAYLOAD" > /dev/null',
    '',
    '    echo "Telemetry SENT -> CPU: $CPU_PCT% | RAM: $RAM_PCT% | IP: $IP"',
    '    sleep $INTERVAL',
    'done'
  ];

  return lines.join('\n');
}
