/**
 * Generates standalone, fully functional monitoring agent scripts
 * with the server URL and device registration token pre-configured or parameter-ready.
 */

function sanitizeServerUrl(url: string): string {
  let u = (url || '').trim();
  if (u.includes('.run.app') || u.includes('cloudrun')) {
    u = u.replace(/^http:\/\//i, 'https://');
  }
  return u;
}

/**
 * The PowerShell agent version is deliberately exported for the Worker update
 * manifest. The dashboard only treats an update as verified after a later
 * authenticated telemetry upload reports this exact version and capabilities.
 */
export const POWERSHELL_AGENT_VERSION = '2.6.1-ps1';
export const POWERSHELL_AGENT_CAPABILITIES = ['wifi_diagnostics', 'network_diagnostic_commands', 'agent_self_update'] as const;

export function generatePowerShellAgent(serverUrl: string, registrationCode: string = '', expectedDeviceId: string = ''): string {
  const cleanUrl = sanitizeServerUrl(serverUrl);
  const lines = [
    '# =====================================================================',
    '# PC & Laptop Hardware Monitoring & Diagnostic Agent (Windows PowerShell)',
    '# =====================================================================',
    '# This lightweight agent collects real hardware telemetry and sends heartbeats',
    '# to the central IT Monitoring & Diagnostic Management Server.',
    '# Compatible with Windows 10, 11, and Windows Server (PowerShell 5.1+ / 7+)',
    '# =====================================================================',
    '',
    'param (',
    `    [string]$ServerUrl = "${cleanUrl}",`,
    `    [string]$RegistrationCode = "${registrationCode}",`,
    `    [string]$ExpectedDeviceId = "${expectedDeviceId}",`,
    '    [int]$IntervalSeconds = 10,',
    '    [int]$NetworkDiagnosticIntervalSeconds = 60,',
    '    [switch]$SkipPreflightCheck,',
    '    [switch]$VerboseConnectivity,',
    '    [switch]$InstallAsStartupTask',
    ')',
    '',
    '# TLS 1.3 is not an enum value in Windows PowerShell 5.1 / .NET Framework.',
    '# Start with TLS 1.2, then opt into TLS 1.3 only when the local runtime supports it.',
    '[Net.ServicePointManager]::SecurityProtocol = [Net.SecurityProtocolType]::Tls12',
    'if ([Enum]::GetNames([Net.SecurityProtocolType]) -contains "Tls13") {',
    '    [Net.ServicePointManager]::SecurityProtocol = [Net.ServicePointManager]::SecurityProtocol -bor [Net.SecurityProtocolType]::Tls13',
    '}',
    '',
    '# A scheduled task, a manual launch, and an update restart must never collect',
    '# and post duplicate telemetry at the same time for one Windows user.',
    '$agentMutexCreated = $false',
    '$agentMutex = New-Object System.Threading.Mutex($true, "Local\\PCMonitoringAgent_$($env:USERNAME)", [ref]$agentMutexCreated)',
    'if (-not $agentMutexCreated -and -not $InstallAsStartupTask) {',
    '    Write-Host "[INFO] Another PC Monitoring Agent instance is already running for this user. Exiting." -ForegroundColor Yellow',
    '    exit 0',
    '}',
    '',
    'if ($ServerUrl -match "^http://.*\\.run\\.app") {',
    '    $ServerUrl = $ServerUrl -replace "^http://", "https://"',
    '}',
    '',
    '# Startup-task installation is intentionally deferred until after local credentials are loaded.',
    '# This lets a paired agent update itself without asking for a consumed registration code.',
    '',
    'Write-Host ""',
    'Write-Host "=======================================================================" -ForegroundColor Cyan',
    'Write-Host "     PC & LAPTOP HARDWARE MONITORING AGENT (WINDOWS POWERSHELL)        " -ForegroundColor Cyan',
    'Write-Host "=======================================================================" -ForegroundColor Cyan',
    'Write-Host " Target Server       : $ServerUrl" -ForegroundColor White',
    'Write-Host " Registration       : $(if ($RegistrationCode) { \'Package registration code supplied\' } else { \'Uses saved credential or prompts if unpaired\' })" -ForegroundColor Gray',
    'Write-Host " Polling Interval    : $IntervalSeconds seconds" -ForegroundColor Gray',
    'Write-Host ""',
    '',
    '# ---------------------------------------------------------------------',
    '# Verbose Pre-Flight Connectivity & Latency Testing Function',
    '# ---------------------------------------------------------------------',
    'function Test-AgentServerConnectivity {',
    '    param (',
    '        [string]$TargetUrl',
    '    )',
    '',
    '    Write-Host "[PRE-FLIGHT] Testing connectivity to backend server..." -ForegroundColor Cyan',
    '',
    '    $uri = $null',
    '    try {',
    '        $uri = [System.Uri]$TargetUrl',
    '    } catch {',
    '        Write-Host "  [FAIL] Invalid Server URL format: $TargetUrl" -ForegroundColor Red',
    '        return @{ Success = $false; ErrorType = "INVALID_URL"; Message = "Invalid URL format" }',
    '    }',
    '',
    '    $targetHost = $uri.Host',
    '    $targetPort = if ($uri.Port -gt 0) { $uri.Port } else { if ($uri.Scheme -eq "https") { 443 } else { 80 } }',
    '',
    '    # 1. DNS Resolution Check',
    '    Write-Host "  1. DNS Resolution ($targetHost)... " -NoNewline -ForegroundColor Gray',
    '    $dnsResolved = $false',
    '    try {',
    '        $ipAddresses = [System.Net.Dns]::GetHostAddresses($targetHost)',
    '        if ($ipAddresses -and $ipAddresses.Count -gt 0) {',
    '            $resolvedIp = $ipAddresses[0].IPAddressToString',
    '            Write-Host "PASS [IP: $resolvedIp]" -ForegroundColor Green',
    '            $dnsResolved = $true',
    '        } else {',
    '            Write-Host "FAIL (No IP returned)" -ForegroundColor Red',
    '        }',
    '    } catch {',
    '        Write-Host "FAIL ($($_.Exception.Message))" -ForegroundColor Red',
    '        return @{ Success = $false; ErrorType = "DNS_FAILURE"; Message = $_.Exception.Message }',
    '    }',
    '',
    '    # 2. TCP Port / Socket Handshake Check',
    '    Write-Host "  2. TCP Socket Handshake ($targetHost : $targetPort)... " -NoNewline -ForegroundColor Gray',
    '    $tcpClient = New-Object System.Net.Sockets.TcpClient',
    '    $sw = [System.Diagnostics.Stopwatch]::StartNew()',
    '    $tcpConnected = $false',
    '    try {',
    '        $connectTask = $tcpClient.ConnectAsync($targetHost, $targetPort)',
    '        if ($connectTask.Wait(4000)) {',
    '            $sw.Stop()',
    '            Write-Host "PASS [Latency: $($sw.ElapsedMilliseconds)ms]" -ForegroundColor Green',
    '            $tcpConnected = $true',
    '        } else {',
    '            Write-Host "TIMEOUT (Port $targetPort unreachable after 4000ms)" -ForegroundColor Red',
    '            $tcpClient.Close()',
    '            return @{ Success = $false; ErrorType = "TCP_TIMEOUT"; Message = "TCP connection timed out" }',
    '        }',
    '    } catch {',
    '        Write-Host "FAIL ($($_.Exception.Message))" -ForegroundColor Red',
    '        return @{ Success = $false; ErrorType = "TCP_CONNECT_FAIL"; Message = $_.Exception.Message }',
    '    } finally {',
    '        try { $tcpClient.Close() } catch { }',
    '    }',
    '',
    '    # 3. HTTP Health & REST API Probe Check',
    '    Write-Host "  3. REST API Endpoint Health Probe (/api/health)... " -NoNewline -ForegroundColor Gray',
    '    $healthUrl = "$($TargetUrl.TrimEnd(\'/\'))/api/health"',
    '    try {',
    '        $httpReq = [System.Net.HttpWebRequest]::Create($healthUrl)',
    '        $httpReq.Timeout = 6000',
    '        $httpReq.Method = "GET"',
    '        $httpReq.UserAgent = "PC-Monitoring-Agent/2.4 (Windows NT)"',
    '        $httpRes = [System.Net.HttpWebResponse]$httpReq.GetResponse()',
    '        $resCode = [int]$httpRes.StatusCode',
    '        $reader = New-Object System.IO.StreamReader($httpRes.GetResponseStream())',
    '        $body = $reader.ReadToEnd()',
    '        $reader.Close()',
    '        $httpRes.Close()',
    '',
    '        if ($body -match "<html" -or $body -match "<!DOCTYPE") {',
    '            Write-Host "WARNING (Received HTML page / Auth challenge)" -ForegroundColor Yellow',
    '            return @{ Success = $false; ErrorType = "HTML_GATEWAY"; StatusCode = $resCode; Message = "Gateway returned HTML login/auth redirect" }',
    '        }',
    '',
    '        Write-Host "PASS [HTTP $resCode - API Ready]" -ForegroundColor Green',
    '        return @{ Success = $true; StatusCode = $resCode }',
    '    } catch [System.Net.WebException] {',
    '        $we = $_.Exception',
    '        if ($we.Response) {',
    '            $errRes = [System.Net.HttpWebResponse]$we.Response',
    '            $errCode = [int]$errRes.StatusCode',
    '            if ($errCode -eq 404) {',
    '                Write-Host "FAIL (HTTP 404 Not Found)" -ForegroundColor Red',
    '                return @{ Success = $false; ErrorType = "HTTP_404"; StatusCode = 404; Message = "API endpoint not found" }',
    '            } elseif ($errCode -eq 401 -or $errCode -eq 403) {',
    '                Write-Host "WARN (HTTP $errCode - Auth Required)" -ForegroundColor Yellow',
    '                return @{ Success = $false; ErrorType = "HTTP_AUTH"; StatusCode = $errCode; Message = "Authentication required" }',
    '            } else {',
    '                Write-Host "FAIL (HTTP $errCode)" -ForegroundColor Red',
    '                return @{ Success = $false; ErrorType = "HTTP_ERROR"; StatusCode = $errCode; Message = $we.Message }',
    '            }',
    '        }',
    '        Write-Host "FAIL ($($we.Message))" -ForegroundColor Red',
    '        return @{ Success = $false; ErrorType = "TIMEOUT_OR_NETWORK"; Message = $we.Message }',
    '    } catch {',
    '        Write-Host "FAIL ($($_.Exception.Message))" -ForegroundColor Red',
    '        return @{ Success = $false; ErrorType = "PROBE_EXCEPTION"; Message = $_.Exception.Message }',
    '    }',
    '}',
    '',
    '# ---------------------------------------------------------------------',
    '# Comprehensive Connection Diagnostic & Troubleshooting Guide',
    '# ---------------------------------------------------------------------',
    'function Show-ConnectionDiagnosticGuide {',
    '    param (',
    '        [string]$Stage,',
    '        [System.Management.Automation.ErrorRecord]$ErrRecord,',
    '        [string]$CustomDetails = "",',
    '        [int]$ExplicitStatusCode = 0,',
    '        [string]$ExplicitErrorType = ""',
    '    )',
    '',
    '    $statusCode = $ExplicitStatusCode',
    '    $statusDesc = ""',
    '    $responseBody = ""',
    '    $isDevSandbox = ($ServerUrl -match "ais-dev-" -or $ServerUrl -match "cloudrun\\.app")',
    '    $isHtmlResponse = $false',
    '    $isTimeout = $false',
    '',
    '    if ($ErrRecord -and $ErrRecord.Exception) {',
    '        $ex = $ErrRecord.Exception',
    '        if ($ex.Message -match "timed out" -or $ex.Message -match "timeout" -or $ex -is [System.TimeoutException]) {',
    '            $isTimeout = $true',
    '        }',
    '        if ($ex -is [System.Net.WebException]) {',
    '            if ($ex.Status -eq [System.Net.WebExceptionStatus]::Timeout -or $ex.Status -eq [System.Net.WebExceptionStatus]::ConnectFailure) {',
    '                $isTimeout = $true',
    '            }',
    '            if ($ex.Response) {',
    '                try {',
    '                    $httpRes = [System.Net.HttpWebResponse]$ex.Response',
    '                    $statusCode = [int]$httpRes.StatusCode',
    '                    $statusDesc = $httpRes.StatusDescription',
    '                    $reader = New-Object System.IO.StreamReader($httpRes.GetResponseStream())',
    '                    $responseBody = $reader.ReadToEnd()',
    '                    $reader.Close()',
    '                    if ($responseBody -match "<html" -or $responseBody -match "<!DOCTYPE" -or $responseBody -match "display: flex") {',
    '                        $isHtmlResponse = $true',
    '                    }',
    '                } catch { }',
    '            }',
    '        }',
    '    }',
    '',
    '    Write-Host ""',
    '    Write-Host "+-----------------------------------------------------------------------------------+" -ForegroundColor Red',
    '    Write-Host "|                        AGENT CONNECTION & DIAGNOSTIC GUIDE                        |" -ForegroundColor Red',
    '    Write-Host "+-----------------------------------------------------------------------------------+" -ForegroundColor Red',
    '    Write-Host " [FAILURE STAGE]  : $Stage" -ForegroundColor White',
    '    Write-Host " [TARGET SERVER]  : $ServerUrl" -ForegroundColor Gray',
    '    if ($statusCode -gt 0) {',
    '        Write-Host " [HTTP STATUS]    : $statusCode ($statusDesc)" -ForegroundColor Red',
    '    }',
    '    if ($CustomDetails) {',
    '        Write-Host " [ERROR DETAILS]  : $CustomDetails" -ForegroundColor Yellow',
    '    }',
    '    Write-Host ""',
    '',
    '    # -----------------------------------------------------------------',
    '    # CASE 1: HTTP 404 Not Found (Server route does not exist)',
    '    # -----------------------------------------------------------------',
    '    if ($statusCode -eq 404 -or $ExplicitErrorType -eq "HTTP_404") {',
    '        Write-Host ">>> [DIAGNOSIS: HTTP 404 - ENDPOINT NOT FOUND] <<<" -ForegroundColor Red',
    '        Write-Host " The target server responded, but the requested agent route was not found." -ForegroundColor White',
    '        Write-Host " Root Cause: The server is either pointing to an un-deployed container or a wrong port." -ForegroundColor Gray',
    '        Write-Host ""',
    '        Write-Host "TROUBLESHOOTING & FIX ACTIONS:" -ForegroundColor Green',
    '        Write-Host " 1. If running locally, verify the backend is active and connect directly with:" -ForegroundColor White',
    '        Write-Host "    .\\pc-monitoring-agent.ps1 -ServerUrl `"http://localhost:3000`" -RegistrationCode `"$RegistrationCode`"" -ForegroundColor Cyan',
    '        Write-Host " 2. Verify there are no trailing paths in ServerUrl (e.g., use http://localhost:3000, not .../api)." -ForegroundColor White',
    '        Write-Host " 3. In the browser, verify http://localhost:3000/api/health returns status ok." -ForegroundColor White',
    '    }',
    '',
    '    # -----------------------------------------------------------------',
    '    # CASE 2: HTTP 401 Unauthorized / Bad Registration Code',
    '    # -----------------------------------------------------------------',
    '    elseif ($statusCode -eq 401 -or $ExplicitErrorType -eq "HTTP_401") {',
    '        Write-Host ">>> [DIAGNOSIS: HTTP 401 - UNAUTHORIZED / INVALID REGISTRATION CODE] <<<" -ForegroundColor Magenta',
    '        Write-Host " The server rejected the request because the registration code is invalid, expired," -ForegroundColor White',
    '        Write-Host " or the cached device token has been revoked or reset." -ForegroundColor White',
    '        Write-Host ""',
    '        Write-Host "TROUBLESHOOTING & FIX ACTIONS:" -ForegroundColor Green',
    '        Write-Host " 1. Open the Web Dashboard -> Click Devices -> Click Install Agent on your target computer." -ForegroundColor White',
    '        Write-Host " 2. Copy the full registration code shown in the Web Dashboard." -ForegroundColor White',
    '        Write-Host " 3. Clear any stale cached token file by executing:" -ForegroundColor White',
    '        Write-Host "    Remove-Item `"`$env:LOCALAPPDATA\\PCMonitoringAgent\\agent-credential.json`" -Force -ErrorAction SilentlyContinue" -ForegroundColor Cyan',
    '        Write-Host " 4. Re-run the agent with your fresh registration code:" -ForegroundColor White',
    '        Write-Host "    .\\pc-monitoring-agent.ps1 -RegistrationCode `"REG-YOUR-CODE`"" -ForegroundColor Cyan',
    '    }',
    '',
    '    # -----------------------------------------------------------------',
    '    # CASE 3: Cloud Sandbox Gateway / HTML Auth Challenge (ais-dev-...)',
    '    # -----------------------------------------------------------------',
    '    elseif ($isHtmlResponse -or ($statusCode -eq 403) -or ($isDevSandbox -and -not $statusCode)) {',
    '        Write-Host ">>> [DIAGNOSIS: GOOGLE AI STUDIO SANDBOX AUTHENTICATION BARRIER] <<<" -ForegroundColor Yellow',
    '        Write-Host " The target server ($ServerUrl) is a private Google AI Studio cloud development sandbox." -ForegroundColor White',
    '        Write-Host " These containers are protected by Google browser session authentication. Direct external CLI tools" -ForegroundColor Gray',
    '        Write-Host " (like PowerShell Invoke-RestMethod) running on remote PCs are blocked by the preview proxy." -ForegroundColor Gray',
    '        Write-Host ""',
    '        Write-Host "RECOMMENDED SOLUTIONS:" -ForegroundColor Green',
    '        Write-Host " * OPTION A (Zero-Setup & Instant Test):" -ForegroundColor Cyan',
    '        Write-Host "   Click the Dev Simulator button in the Web Dashboard navbar to simulate real-time" -ForegroundColor White',
    '        Write-Host "   CPU, RAM, temperature spikes, disk alerts, and automated ticket generation immediately." -ForegroundColor White',
    '        Write-Host ""',
    '        Write-Host " * OPTION B (Monitor Real Physical PC Hardware):" -ForegroundColor Cyan',
    '        Write-Host "   Run this application locally on your machine (npm run dev) and connect your agent to:" -ForegroundColor White',
    '        Write-Host "   .\\pc-monitoring-agent.ps1 -ServerUrl `"http://localhost:3000`" -RegistrationCode `"$RegistrationCode`"" -ForegroundColor Yellow',
    '    }',
    '',
    '    # -----------------------------------------------------------------',
    '    # CASE 4: Network Timeout & TCP Connection Failures',
    '    # -----------------------------------------------------------------',
    '    elseif ($isTimeout -or $ExplicitErrorType -eq "TCP_TIMEOUT" -or $ExplicitErrorType -eq "TIMEOUT_OR_NETWORK") {',
    '        Write-Host ">>> [DIAGNOSIS: NETWORK TIMEOUT / HOST UNREACHABLE] <<<" -ForegroundColor Red',
    '        Write-Host " The agent could not establish a TCP connection to $ServerUrl within the timeout limit." -ForegroundColor White',
    '        Write-Host " Possible Causes: Offline network adapter, firewall blocking port, or server not running." -ForegroundColor Gray',
    '        Write-Host ""',
    '        Write-Host "TROUBLESHOOTING & FIX ACTIONS:" -ForegroundColor Green',
    '        Write-Host " 1. Check if the server is running on the host machine." -ForegroundColor White',
    '        Write-Host " 2. Test port reachability using PowerShell:" -ForegroundColor White',
    '        Write-Host "    Test-NetConnection -ComputerName (([System.Uri]`"$ServerUrl`").Host) -Port (([System.Uri]`"$ServerUrl`").Port)" -ForegroundColor Cyan',
    '        Write-Host " 3. Verify that your firewall or corporate proxy allows outbound HTTP/HTTPS traffic." -ForegroundColor White',
    '    }',
    '',
    '    # -----------------------------------------------------------------',
    '    # CASE 5: DNS Name Resolution Failure',
    '    # -----------------------------------------------------------------',
    '    elseif ($ExplicitErrorType -eq "DNS_FAILURE") {',
    '        Write-Host ">>> [DIAGNOSIS: DNS NAME RESOLUTION FAILED] <<<" -ForegroundColor Red',
    '        Write-Host " Could not resolve host: $ServerUrl" -ForegroundColor White',
    '        Write-Host "TROUBLESHOOTING & FIX ACTIONS:" -ForegroundColor Green',
    '        Write-Host " 1. Verify hostname spelling." -ForegroundColor White',
    '        Write-Host " 2. Test DNS resolution via: Resolve-DnsName (([System.Uri]`"$ServerUrl`").Host)" -ForegroundColor Cyan',
    '    }',
    '',
    '    # -----------------------------------------------------------------',
    '    # CASE 6: Server 5xx Internal Errors',
    '    # -----------------------------------------------------------------',
    '    elseif ($statusCode -ge 500) {',
    '        Write-Host ">>> [DIAGNOSIS: SERVER INTERNAL ERROR (HTTP $statusCode)] <<<" -ForegroundColor Red',
    '        Write-Host " The management server encountered an internal error or is in the middle of restarting." -ForegroundColor White',
    '        Write-Host "TROUBLESHOOTING & FIX ACTIONS:" -ForegroundColor Green',
    '        Write-Host " 1. Wait 10-15 seconds for the server to finish rebooting and re-run." -ForegroundColor White',
    '    }',
    '    else {',
    '        Write-Host ">>> [DIAGNOSIS: GENERAL CONNECTION FAILURE] <<<" -ForegroundColor Red',
    '        Write-Host " Error Details: $($ErrRecord.Exception.Message)" -ForegroundColor White',
    '        Write-Host "TROUBLESHOOTING & FIX ACTIONS:" -ForegroundColor Green',
    '        Write-Host " 1. Verify target server is active and accessible." -ForegroundColor White',
    '        Write-Host " 2. Test connection with: Invoke-RestMethod -Uri `"$ServerUrl/api/health`" -TimeoutSec 5" -ForegroundColor Cyan',
    '    }',
    '    Write-Host "+-----------------------------------------------------------------------------------+" -ForegroundColor Red',
    '    Write-Host ""',
    '}',
    '',
    '# Execute Pre-Flight Connectivity Check unless explicitly skipped',
    'if (-not $SkipPreflightCheck) {',
    '    $preflight = Test-AgentServerConnectivity -TargetUrl $ServerUrl',
    '    if (-not $preflight.Success) {',
    '        Show-ConnectionDiagnosticGuide -Stage "Pre-Flight Connectivity Check" -ErrRecord $null -ExplicitStatusCode ($preflight.StatusCode) -ExplicitErrorType ($preflight.ErrorType) -CustomDetails ($preflight.Message)',
    '        Write-Host "[NOTICE] Continuing with registration attempt in 3 seconds..." -ForegroundColor Gray',
    '        Start-Sleep -Seconds 3',
    '    } else {',
    '        Write-Host "[SUCCESS] Pre-flight connectivity verified successfully!" -ForegroundColor Green',
    '        Write-Host ""',
    '    }',
    '}',
    '',
    '# The credential is scoped to the Windows user using DPAPI. Older agents',
    '# stored a plain JSON token in TEMP; it is read once and migrated safely.',
    '$AgentDirectory = Join-Path $env:LOCALAPPDATA "PCMonitoringAgent"',
    '$CredentialFile = Join-Path $AgentDirectory "agent-credential.json"',
    '$LegacyTokenFile = Join-Path $env:TEMP "pc_monitoring_agent_token.json"',
    '$UpdateReceiptFile = Join-Path $AgentDirectory "agent-update-receipt.json"',
    '$DeviceToken = $null',
    '$DeviceId = $null',
    '',
    'function Save-AgentCredential {',
    '    param([string]$Token, [string]$Id)',
    '    New-Item -ItemType Directory -Path $AgentDirectory -Force | Out-Null',
    '    $protectedToken = ConvertTo-SecureString -String $Token -AsPlainText -Force | ConvertFrom-SecureString',
    '    @{ formatVersion = 1; server = $ServerUrl.TrimEnd("/"); protectedToken = $protectedToken; deviceId = $Id; savedAt = (Get-Date).ToUniversalTime().ToString("o") } | ConvertTo-Json | Set-Content -LiteralPath $CredentialFile -Encoding UTF8',
    '}',
    '',
    'function Read-AgentProtectedToken {',
    '    param([string]$ProtectedToken)',
    '    $secure = ConvertTo-SecureString -String $ProtectedToken',
    '    $ptr = [Runtime.InteropServices.Marshal]::SecureStringToBSTR($secure)',
    '    try { return [Runtime.InteropServices.Marshal]::PtrToStringBSTR($ptr) } finally { [Runtime.InteropServices.Marshal]::ZeroFreeBSTR($ptr) }',
    '}',
    '',
    'function Load-AgentCredential {',
    '    if (Test-Path $CredentialFile) {',
    '        try {',
    '            $cached = Get-Content -LiteralPath $CredentialFile -Raw | ConvertFrom-Json',
    '            if ($cached.server -eq $ServerUrl.TrimEnd("/") -and $cached.protectedToken -and $cached.deviceId) {',
    '                return @{ token = (Read-AgentProtectedToken -ProtectedToken $cached.protectedToken); deviceId = [string]$cached.deviceId }',
    '            }',
    '        } catch { Write-Host "[WARN] Could not read the protected agent credential." -ForegroundColor Yellow }',
    '    }',
    '    if (Test-Path $LegacyTokenFile) {',
    '        try {',
    '            $legacy = Get-Content -LiteralPath $LegacyTokenFile -Raw | ConvertFrom-Json',
    '            $legacyToken = if ($legacy.token) { [string]$legacy.token } else { [string]$legacy.deviceToken }',
    '            if ($legacy.server -eq $ServerUrl -and $legacyToken -and $legacy.deviceId) {',
    '                Save-AgentCredential -Token $legacyToken -Id ([string]$legacy.deviceId)',
    '                Remove-Item -LiteralPath $LegacyTokenFile -Force -ErrorAction SilentlyContinue',
    '                Write-Host "[INFO] Migrated the legacy agent credential into Windows protected storage." -ForegroundColor Green',
    '                return @{ token = $legacyToken; deviceId = [string]$legacy.deviceId }',
    '            }',
    '        } catch { Write-Host "[WARN] Could not migrate the legacy agent credential." -ForegroundColor Yellow }',
    '    }',
    '    return $null',
    '}',
    '',
    '$cachedCredential = Load-AgentCredential',
    'if ($cachedCredential) {',
    '    $DeviceToken = [string]$cachedCredential.token',
    '    $DeviceId = [string]$cachedCredential.deviceId',
    '    Write-Host "[INFO] Loaded protected authentication credential for Device ID: $DeviceId" -ForegroundColor Green',
    '}',
    '',
    '# A package carrying a new registration code is an explicit request to',
    '# pair a new asset. Do not silently reuse a credential from a recycled',
    '# Windows profile; device-bound update packages have ExpectedDeviceId instead.',
    'if ($RegistrationCode -and -not $ExpectedDeviceId) {',
    '    if ($DeviceToken) { Write-Host "[INFO] A new registration code was supplied; replacing the cached pairing after registration." -ForegroundColor Yellow }',
    '    $DeviceToken = $null',
    '    $DeviceId = $null',
    '}',
    '',
    'if ($ExpectedDeviceId -and ((-not $DeviceToken) -or $DeviceId -ne $ExpectedDeviceId)) {',
    '    Write-Host "[ERROR] This update package belongs to a different paired device or no paired credential exists. No files were changed." -ForegroundColor Red',
    '    Exit 1',
    '}',
    '',
    'if (-not $DeviceToken -and -not $RegistrationCode) {',
    '    $RegistrationCode = Read-Host "Enter Device Registration Code (from Web Dashboard)"',
    '}',
    '',
    'if (-not $DeviceToken -and -not $RegistrationCode) {',
    '    Write-Host "[ERROR] A registration code is required until this machine is paired. Exiting." -ForegroundColor Red',
    '    Exit 1',
    '}',
    '',
    '# Install or replace the per-user startup task only after credential validation.',
    'if ($InstallAsStartupTask) {',
    '    try {',
    '        $installedScript = Join-Path $AgentDirectory "pc-monitoring-agent.ps1"',
    '        New-Item -ItemType Directory -Path $AgentDirectory -Force | Out-Null',
    '        Copy-Item -LiteralPath $PSCommandPath -Destination $installedScript -Force',
    '        $taskAction = New-ScheduledTaskAction -Execute "powershell.exe" -Argument ("-NoProfile -ExecutionPolicy Bypass -WindowStyle Hidden -File `"{0}`"" -f $installedScript)',
    '        $taskTrigger = New-ScheduledTaskTrigger -AtLogOn',
    '        Register-ScheduledTask -TaskName "PC Monitoring Agent" -Action $taskAction -Trigger $taskTrigger -Force | Out-Null',
    '        Start-ScheduledTask -TaskName "PC Monitoring Agent"',
    '        Write-Host "[SUCCESS] Agent installed or updated. The next heartbeat will confirm its version." -ForegroundColor Green',
    '        exit 0',
    '    } catch {',
    '        Write-Host "[ERROR] Could not install the automatic startup task: $($_.Exception.Message)" -ForegroundColor Red',
    '        Write-Host "Run PowerShell as the same normal Windows user that runs the existing agent, then try again." -ForegroundColor Yellow',
    '        exit 1',
    '    }',
    '}',
    '',
    '# Function to get OS and Hardware Specs',
    'function Get-SystemHardwareSpecs {',
    '    try {',
    '        $cs = Get-CimInstance Win32_ComputerSystem -ErrorAction SilentlyContinue',
    '        $os = Get-CimInstance Win32_OperatingSystem -ErrorAction SilentlyContinue',
    '        $cpu = Get-CimInstance Win32_Processor -ErrorAction SilentlyContinue | Select-Object -First 1',
    '        $bios = Get-CimInstance Win32_BIOS -ErrorAction SilentlyContinue',
    '        $gpu = Get-CimInstance Win32_VideoController -ErrorAction SilentlyContinue | Select-Object -First 1',
    '',
    '        $isLaptop = $null',
    '        $enc = Get-CimInstance Win32_SystemEnclosure -ErrorAction SilentlyContinue | Select-Object -First 1',
    '        if ($enc -and $enc.ChassisTypes) {',
    '            $isLaptop = ($enc.ChassisTypes -contains 8 -or $enc.ChassisTypes -contains 9 -or $enc.ChassisTypes -contains 10 -or $enc.ChassisTypes -contains 14)',
    '        }',
    '',
    '        $totalRamBytes = $null',
    '        if ($os -and $os.TotalVisibleMemorySize) {',
    '            $totalRamBytes = [int64]$os.TotalVisibleMemorySize * 1024',
    '        }',
    '',
    '        $cpuModel = if ($cpu -and $cpu.Name) { $cpu.Name.Trim() } else { $null }',
    '        $cpuCores = if ($cpu -and $cpu.NumberOfCores) { [int]$cpu.NumberOfCores } else { $null }',
    '        $cpuLogical = if ($cpu -and $cpu.NumberOfLogicalProcessors) { [int]$cpu.NumberOfLogicalProcessors } else { $null }',
    '        $osCaption = if ($os -and $os.Caption) { "$($os.Caption) $($os.OSArchitecture)" } else { $null }',
    '        $osVer = if ($os -and $os.Version) { $os.Version } else { $null }',
    '        $osBuild = if ($os -and $os.BuildNumber) { $os.BuildNumber } else { $null }',
    '        $osArch = if ($os -and $os.OSArchitecture) { $os.OSArchitecture } else { $null }',
    '        $mfg = if ($cs -and $cs.Manufacturer) { "$($cs.Manufacturer) $($cs.Model)" } else { $null }',
    '        $biosVer = if ($bios -and $bios.SMBIOSBIOSVersion) { $bios.SMBIOSBIOSVersion } else { $null }',
    '        $serial = if ($bios -and $bios.SerialNumber) { $bios.SerialNumber } else { $null }',
    '        $gpuName = if ($gpu -and $gpu.Name) { $gpu.Name } else { $null }',
    '',
    '        return @{',
    '            osName = $osCaption',
    '            osVersion = $osVer',
    '            osBuild = $osBuild',
    '            osArchitecture = $osArch',
    '            cpuModel = $cpuModel',
    '            cpuCores = $cpuCores',
    '            cpuLogicalProcessors = $cpuLogical',
    '            totalRamBytes = $totalRamBytes',
    '            motherboard = $mfg',
    '            biosVersion = $biosVer',
    '            serialNumber = $serial',
    '            gpuModel = $gpuName',
    '            isLaptop = $isLaptop',
    '        }',
    '    } catch {',
    '        Write-Host "[WARN] Hardware specs Cim collection error: $($_.Exception.Message)" -ForegroundColor Yellow',
    '        return @{}',
    '    }',
    '}',
    '',
    '# Perform Registration if needed',
    'if (-not $DeviceToken) {',
    '    Write-Host "[INFO] Registering computer with centralized server..." -ForegroundColor Cyan',
    '    $specs = Get-SystemHardwareSpecs',
    '    $computerName = $env:COMPUTERNAME',
    '',
    '    $regPayload = @{',
    '        registrationCode = $RegistrationCode',
    '        computerName = $computerName',
    '        osName = $specs.osName',
    '        osVersion = $specs.osVersion',
    '        osBuild = $specs.osBuild',
    '        osArchitecture = $specs.osArchitecture',
    '        cpuModel = $specs.cpuModel',
    '        cpuCores = $specs.cpuCores',
    '        cpuLogicalProcessors = $specs.cpuLogicalProcessors',
    '        totalRamBytes = $specs.totalRamBytes',
    '        motherboard = $specs.motherboard',
    '        biosVersion = $specs.biosVersion',
    '        serialNumber = $specs.serialNumber',
    '        gpuModel = $specs.gpuModel',
    '        isLaptop = $specs.isLaptop',
    `        agentVersion = "${POWERSHELL_AGENT_VERSION}"`,
    '        agentCapabilities = @("wifi_diagnostics", "network_diagnostic_commands", "agent_self_update")',
    '    } | ConvertTo-Json -Depth 5',
    '',
    '    try {',
    '        $regResponse = Invoke-RestMethod -Uri "$ServerUrl/api/agent/register" -Method Post -ContentType "application/json" -Body $regPayload -TimeoutSec 12',
    '        $token = if ($regResponse.token) { $regResponse.token } else { $regResponse.deviceToken }',
    '        if ($regResponse.success -and $token) {',
    '            $DeviceToken = $token',
    '            $DeviceId = $regResponse.deviceId',
    '            if ($regResponse.heartbeatIntervalSec -and [int]$regResponse.heartbeatIntervalSec -ge 2) { $IntervalSeconds = [int]$regResponse.heartbeatIntervalSec }',
    '            if ($regResponse.networkDiagnosticIntervalSec -and [int]$regResponse.networkDiagnosticIntervalSec -ge 10) { $NetworkDiagnosticIntervalSeconds = [int]$regResponse.networkDiagnosticIntervalSec }',
    '            Write-Host "[SUCCESS] Registered successfully! Assigned Device ID: $DeviceId" -ForegroundColor Green',
    '',
    '            Save-AgentCredential -Token $DeviceToken -Id $DeviceId',
    '        } else {',
    '            $errMsg = if ($regResponse.error) { $regResponse.error } else { ($regResponse | ConvertTo-Json -Compress) }',
    '            Show-ConnectionDiagnosticGuide -Stage "Device Registration" -ErrRecord $null -CustomDetails "Server rejected registration: $errMsg"',
    '            Exit 1',
    '        }',
    '    } catch {',
    '        Show-ConnectionDiagnosticGuide -Stage "Device Registration (POST /api/agent/register)" -ErrRecord $_',
    '        Exit 1',
    '    }',
    '}',
    '',
    'Write-Host "=======================================================================" -ForegroundColor Green',
    'Write-Host ">>> REAL-TIME TELEMETRY ENGINE ACTIVE (Ctrl+C to stop) <<<" -ForegroundColor Green',
    'Write-Host "=======================================================================" -ForegroundColor Green',
    '',
    '$consecutiveErrors = 0',
    '$lastWiFiDiagnostics = $null',
    '$lastNetworkDiagnosticAt = [datetime]::MinValue',
    '$forceNetworkDiagnostic = $true',
    '$pendingCommandResults = @()',
    '$pendingUpdateReceipt = $null',
    'if (Test-Path $UpdateReceiptFile) {',
    '    try {',
    '        $pendingUpdateReceipt = Get-Content -LiteralPath $UpdateReceiptFile -Raw | ConvertFrom-Json',
    '        if ($pendingUpdateReceipt.commandId -and $pendingUpdateReceipt.targetVersion) {',
    '            $pendingCommandResults += @{ id = [string]$pendingUpdateReceipt.commandId; type = "agent_update"; status = "applied"; targetVersion = [string]$pendingUpdateReceipt.targetVersion; appliedAt = [string]$pendingUpdateReceipt.appliedAt }',
    '            Write-Host "[UPDATE] Reporting agent update evidence for $($pendingUpdateReceipt.targetVersion)." -ForegroundColor Cyan',
    '        }',
    '    } catch { Write-Host "[WARN] Could not read the pending agent update receipt." -ForegroundColor Yellow }',
    '}',
    '',
    'function Invoke-AgentSelfUpdate {',
    '    param($Command, [hashtable]$Headers)',
    '    try {',
    '        if (-not $ServerUrl.StartsWith("https://", [System.StringComparison]::OrdinalIgnoreCase)) { throw "Automatic updates require an HTTPS server URL." }',
    '        $baseUrl = $ServerUrl.TrimEnd("/")',
    '        $manifest = Invoke-RestMethod -Uri "$baseUrl/api/agent/update/powershell/manifest?deviceId=$DeviceId" -Method Get -Headers $Headers -TimeoutSec 20',
    '        if (-not $manifest.version -or -not $manifest.sha256 -or $manifest.deviceId -ne $DeviceId) { throw "The update manifest is incomplete or is for another device." }',
    '        $package = Invoke-WebRequest -Uri "$baseUrl/api/agent/update/powershell/package?deviceId=$DeviceId" -Method Get -Headers $Headers -TimeoutSec 45 -UseBasicParsing',
    '        $stagePath = Join-Path $AgentDirectory "pc-monitoring-agent.ps1.new"',
    '        [System.IO.File]::WriteAllText($stagePath, [string]$package.Content, (New-Object System.Text.UTF8Encoding($false)))',
    '        $actualHash = (Get-FileHash -LiteralPath $stagePath -Algorithm SHA256).Hash.ToLowerInvariant()',
    '        if ($actualHash -ne ([string]$manifest.sha256).ToLowerInvariant()) { Remove-Item -LiteralPath $stagePath -Force -ErrorAction SilentlyContinue; throw "Downloaded package integrity check failed." }',
    '        $tokens = $null; $parseErrors = $null',
    '        [System.Management.Automation.Language.Parser]::ParseFile($stagePath, [ref]$tokens, [ref]$parseErrors) | Out-Null',
    '        if ($parseErrors -and $parseErrors.Count -gt 0) { Remove-Item -LiteralPath $stagePath -Force -ErrorAction SilentlyContinue; throw "Downloaded package did not pass PowerShell syntax validation." }',
    '        $installedScript = Join-Path $AgentDirectory "pc-monitoring-agent.ps1"',
    '        if (Test-Path $installedScript) { Copy-Item -LiteralPath $installedScript -Destination "$installedScript.previous" -Force }',
    '        Move-Item -LiteralPath $stagePath -Destination $installedScript -Force',
    '        @{ commandId = [string]$Command.id; targetVersion = [string]$manifest.version; appliedAt = (Get-Date).ToUniversalTime().ToString("o") } | ConvertTo-Json | Set-Content -LiteralPath $UpdateReceiptFile -Encoding UTF8',
    '        Write-Host "[UPDATE] Verified package hash. Restarting the monitoring agent to apply $($manifest.version)." -ForegroundColor Green',
    '        Start-Process -FilePath "powershell.exe" -ArgumentList ("-NoProfile -ExecutionPolicy Bypass -WindowStyle Hidden -File `"{0}`"" -f $installedScript) -WindowStyle Hidden',
    '        return @{ success = $true; version = [string]$manifest.version }',
    '    } catch {',
    '        return @{ success = $false; error = $_.Exception.Message }',
    '    }',
    '}',
    '',
    String.raw`
# ---------------------------------------------------------------------
# Real Windows Wi-Fi connectivity diagnostics. No values in this result
# are fabricated: unavailable fields remain null and unavailable tests
# remain null so the central console can distinguish them from failures.
# ---------------------------------------------------------------------
function Get-WifiDiagnostics {
    $testedAt = (Get-Date).ToUniversalTime().ToString("o")
    $result = [ordered]@{
        available = $false
        adapterName = $null
        adapterStatus = "NOT AVAILABLE"
        connectionState = "NOT AVAILABLE"
        ssid = $null
        bssid = $null
        signalQuality = $null
        radioType = $null
        band = $null
        frequencyMhz = $null
        channel = $null
        linkSpeedMbps = $null
        receiveLinkSpeedMbps = $null
        transmitLinkSpeedMbps = $null
        ipv4 = $null
        ipv6 = $null
        subnetMask = $null
        defaultGateway = $null
        defaultGatewayIpv6 = $null
        dnsServers = @()
        dhcpEnabled = $null
        dhcpServer = $null
        networkProfile = $null
        networkCategory = $null
        mac = $null
        connectionObservedSince = $null
        connectionDurationSeconds = $null
        gatewayReachable = $null
        gatewayLatencyMs = $null
        gatewayProbeMethod = $null
        dnsResolution = $null
        dnsResponseTimeMs = $null
        internetReachable = $null
        internetIcmpReachable = $null
        internetHttpReachable = $null
        packetLossPercent = $null
        avgLatencyMs = $null
        minLatencyMs = $null
        maxLatencyMs = $null
        failedProbes = $null
        responseTimeMs = $null
        testedAt = $testedAt
    }

    $wifiAdapter = $null
    $netshFields = @{}
    try {
        $netshLines = @(netsh wlan show interfaces 2>$null)
        foreach ($line in $netshLines) {
            if ($line -match '^\s*([^:]+?)\s*:\s*(.*)$') {
                $key = $matches[1].Trim().ToLowerInvariant()
                $netshFields[$key] = $matches[2].Trim()
            }
        }
    } catch { }

    # Prefer the adapter named by netsh. Selecting the first wireless-looking
    # adapter can choose a disconnected virtual interface while another
    # physical adapter is actively associated with the SSID.
    try {
        $netshInterfaceName = if ($netshFields.ContainsKey("name")) { [string]$netshFields["name"] } else { "" }
        if ($netshInterfaceName) {
            $wifiAdapter = Get-NetAdapter -Name $netshInterfaceName -IncludeHidden -ErrorAction SilentlyContinue | Select-Object -First 1
        }
        if (-not $wifiAdapter) {
            $wifiAdapter = Get-NetAdapter -IncludeHidden -ErrorAction Stop | Where-Object {
                ($_.NdisPhysicalMedium -eq "Native 802.11" -or $_.InterfaceDescription -match "Wireless|Wi-Fi|802\.11") -and $_.Status -eq "Up"
            } | Select-Object -First 1
        }
        if (-not $wifiAdapter) {
            $wifiAdapter = Get-NetAdapter -IncludeHidden -ErrorAction Stop | Where-Object {
                $_.NdisPhysicalMedium -eq "Native 802.11" -or $_.InterfaceDescription -match "Wireless|Wi-Fi|802\.11"
            } | Select-Object -First 1
        }
    } catch { }

    if ($wifiAdapter -or $netshFields.ContainsKey("name") -or $netshFields.ContainsKey("state")) {
        $result.available = $true
    } else {
        return [pscustomobject]$result
    }

    $interfaceIndex = $null
    if ($wifiAdapter) {
        $result.adapterName = $wifiAdapter.Name
        $result.adapterStatus = [string]$wifiAdapter.Status
        $interfaceIndex = $wifiAdapter.ifIndex
        if ($wifiAdapter.MacAddress) { $result.mac = [string]$wifiAdapter.MacAddress }
    }
    if (-not $result.adapterName -and $netshFields.ContainsKey("name")) { $result.adapterName = $netshFields["name"] }
    if ($netshFields.ContainsKey("description") -and -not $result.adapterName) { $result.adapterName = $netshFields["description"] }

    $netshState = if ($netshFields.ContainsKey("state")) { [string]$netshFields["state"] } else { "" }
    $stateNormalized = $netshState.Trim().ToLowerInvariant()
    $adapterUnavailable = [string]$result.adapterStatus -match "Disabled|Disconnected|Not Present"
    if ($stateNormalized -eq "connected" -and -not $adapterUnavailable) {
        $result.connectionState = "CONNECTED"
    } elseif ([string]$result.adapterStatus -match "Disabled") {
        $result.connectionState = "DISABLED"
    } elseif ($stateNormalized -eq "disconnected" -or [string]$result.adapterStatus -match "Disconnected|Not Present") {
        $result.connectionState = "DISCONNECTED"
    } else {
        $result.connectionState = "ERROR"
    }

    if ($netshFields.ContainsKey("ssid")) { $result.ssid = $netshFields["ssid"] }
    if ($netshFields.ContainsKey("bssid")) { $result.bssid = $netshFields["bssid"] }
    if ($netshFields.ContainsKey("radio type")) { $result.radioType = $netshFields["radio type"] }
    if ($netshFields.ContainsKey("band")) { $result.band = $netshFields["band"] }
    if ($netshFields.ContainsKey("channel") -and $netshFields["channel"] -match "(\d+)") { $result.channel = [int]$matches[1] }
    if ($netshFields.ContainsKey("signal") -and $netshFields["signal"] -match "(\d+)\s*%") { $result.signalQuality = [int]$matches[1] }
    if ($netshFields.ContainsKey("receive rate (mbps)") -and $netshFields["receive rate (mbps)"] -match "([\d\.]+)") { $result.receiveLinkSpeedMbps = [double]$matches[1] }
    if ($netshFields.ContainsKey("transmit rate (mbps)") -and $netshFields["transmit rate (mbps)"] -match "([\d\.]+)") { $result.transmitLinkSpeedMbps = [double]$matches[1] }
    $linkRates = @($result.receiveLinkSpeedMbps, $result.transmitLinkSpeedMbps) | Where-Object { $null -ne $_ }
    if ($linkRates.Count -gt 0) { $result.linkSpeedMbps = [math]::Round(($linkRates | Measure-Object -Maximum).Maximum, 2) }

    if ($interfaceIndex) {
        try {
            $ipConfig = Get-NetIPConfiguration -InterfaceIndex $interfaceIndex -ErrorAction Stop
            $ipv4Address = @($ipConfig.IPv4Address | Where-Object { $_.IPAddress } | Select-Object -First 1)
            $ipv6Address = @($ipConfig.IPv6Address | Where-Object { $_.IPAddress -and $_.IPAddress -notmatch '^fe80:' } | Select-Object -First 1)
            if ($ipv4Address.Count -gt 0) { $result.ipv4 = [string]$ipv4Address[0].IPAddress }
            if ($ipv6Address.Count -gt 0) { $result.ipv6 = [string]$ipv6Address[0].IPAddress }
            if (-not $result.defaultGateway -and $ipConfig.IPv4DefaultGateway) {
                $result.defaultGateway = [string](@($ipConfig.IPv4DefaultGateway | Where-Object { $_.NextHop } | Select-Object -First 1).NextHop)
            }
        } catch { }
        # Get-NetIPConfiguration can omit an address while the adapter is
        # renewing DHCP. Query the address and route tables directly as a
        # second source before classifying the result as a DHCP failure.
        if (-not $result.ipv4) {
            try {
                $directIpv4 = @(Get-NetIPAddress -InterfaceIndex $interfaceIndex -AddressFamily IPv4 -ErrorAction Stop | Where-Object {
                    $_.IPAddress -and $_.IPAddress -notmatch '^(0\.0\.0\.0|127\.|169\.254\.)'
                } | Select-Object -First 1)
                if ($directIpv4.Count -gt 0) { $result.ipv4 = [string]$directIpv4[0].IPAddress }
            } catch { }
        }
        if (-not $result.ipv6) {
            try {
                $directIpv6 = @(Get-NetIPAddress -InterfaceIndex $interfaceIndex -AddressFamily IPv6 -ErrorAction Stop | Where-Object {
                    $_.IPAddress -and $_.IPAddress -notmatch '^fe80:'
                } | Select-Object -First 1)
                if ($directIpv6.Count -gt 0) { $result.ipv6 = [string]$directIpv6[0].IPAddress }
            } catch { }
        }
        try {
            $adapterConfig = Get-CimInstance Win32_NetworkAdapterConfiguration -Filter "InterfaceIndex = $interfaceIndex" -ErrorAction Stop | Select-Object -First 1
            if ($adapterConfig) {
                if (-not $result.ipv4 -and $adapterConfig.IPAddress) { $result.ipv4 = @($adapterConfig.IPAddress | Where-Object { $_ -match '^\d+\.\d+\.\d+\.\d+$' } | Select-Object -First 1)[0] }
                if (-not $result.ipv6 -and $adapterConfig.IPAddress) { $result.ipv6 = @($adapterConfig.IPAddress | Where-Object { $_ -match ':' } | Select-Object -First 1)[0] }
                if ($adapterConfig.IPSubnet) { $result.subnetMask = @($adapterConfig.IPSubnet | Where-Object { $_ -match '^\d+\.\d+\.\d+\.\d+$' } | Select-Object -First 1)[0] }
                if ($adapterConfig.DNSServerSearchOrder) { $result.dnsServers = @($adapterConfig.DNSServerSearchOrder | Where-Object { $_ }) }
                if ($adapterConfig.DefaultIPGateway) { $result.defaultGateway = @($adapterConfig.DefaultIPGateway | Where-Object { $_ -match '^\d+\.\d+\.\d+\.\d+$' } | Select-Object -First 1)[0] }
                $result.dhcpEnabled = [bool]$adapterConfig.DHCPEnabled
                if ($adapterConfig.DHCPServer) { $result.dhcpServer = [string]$adapterConfig.DHCPServer }
                if (-not $result.mac -and $adapterConfig.MACAddress) { $result.mac = [string]$adapterConfig.MACAddress }
            }
        } catch { }
        if (-not $result.defaultGateway) {
            try { $result.defaultGateway = @(Get-NetRoute -InterfaceIndex $interfaceIndex -DestinationPrefix "0.0.0.0/0" -ErrorAction Stop | Where-Object { $_.NextHop -and $_.NextHop -ne "0.0.0.0" } | Select-Object -First 1).NextHop } catch { }
        }
        try { $result.defaultGatewayIpv6 = @(Get-NetRoute -InterfaceIndex $interfaceIndex -DestinationPrefix "::/0" -ErrorAction Stop | Where-Object { $_.NextHop -and $_.NextHop -ne "::" } | Select-Object -First 1).NextHop } catch { }
        try {
            $profile = Get-NetConnectionProfile -InterfaceIndex $interfaceIndex -ErrorAction Stop | Select-Object -First 1
            if ($profile) {
                if ($profile.Name) { $result.networkProfile = [string]$profile.Name }
                if ($profile.NetworkCategory) { $result.networkCategory = [string]$profile.NetworkCategory }
                if ($result.connectionState -eq "ERROR") { $result.connectionState = "CONNECTED" }
            }
        } catch { }
    }

    if ($result.connectionState -eq "CONNECTED") {
        $connectionKey = "$($result.adapterName)|$($result.ssid)|$($result.bssid)"
        if ($script:WiFiObservedConnectionKey -ne $connectionKey -or -not $script:WiFiObservedConnectionAt) {
            $script:WiFiObservedConnectionKey = $connectionKey
            $script:WiFiObservedConnectionAt = Get-Date
        }
        $result.connectionObservedSince = $script:WiFiObservedConnectionAt.ToUniversalTime().ToString("o")
        $result.connectionDurationSeconds = [int]((Get-Date) - $script:WiFiObservedConnectionAt).TotalSeconds
    } else {
        $script:WiFiObservedConnectionKey = $null
        $script:WiFiObservedConnectionAt = $null
    }

    if ($result.connectionState -ne "CONNECTED" -or (-not $result.ipv4 -and -not $result.ipv6)) {
        return [pscustomobject]$result
    }

    if ($result.defaultGateway) {
        try {
            $gatewayWatch = [System.Diagnostics.Stopwatch]::StartNew()
            $gatewayResponses = @(Test-Connection -ComputerName $result.defaultGateway -Count 3 -ErrorAction SilentlyContinue)
            $gatewayWatch.Stop()
            $result.gatewayReachable = $gatewayResponses.Count -gt 0
            $result.gatewayProbeMethod = "ICMP"
            if ($gatewayResponses.Count -gt 0) {
                $gatewayLatencies = @($gatewayResponses | ForEach-Object { if ($null -ne $_.ResponseTime) { [double]$_.ResponseTime } } | Where-Object { $null -ne $_ })
                if ($gatewayLatencies.Count -gt 0) { $result.gatewayLatencyMs = [math]::Round(($gatewayLatencies | Measure-Object -Average).Average, 1) }
            }
        } catch { $result.gatewayReachable = $false; $result.gatewayProbeMethod = "ICMP" }
    }
    if ($result.gatewayReachable -ne $true) {
        return [pscustomobject]$result
    }

    try {
        $internetResponses = @(Test-Connection -ComputerName "1.1.1.1" -Count 4 -ErrorAction SilentlyContinue)
        $successfulProbes = $internetResponses.Count
        $result.internetIcmpReachable = $successfulProbes -gt 0
        $result.failedProbes = 4 - $successfulProbes
        $latencies = @($internetResponses | ForEach-Object { if ($null -ne $_.ResponseTime) { [double]$_.ResponseTime } elseif ($null -ne $_.Latency) { [double]$_.Latency } } | Where-Object { $null -ne $_ })
        if ($latencies.Count -gt 0) {
            $result.packetLossPercent = [math]::Round((($result.failedProbes / 4) * 100), 1)
            $result.avgLatencyMs = [math]::Round(($latencies | Measure-Object -Average).Average, 1)
            $result.minLatencyMs = [math]::Round(($latencies | Measure-Object -Minimum).Minimum, 1)
            $result.maxLatencyMs = [math]::Round(($latencies | Measure-Object -Maximum).Maximum, 1)
        }
    } catch { }
    try {
        $dnsWatch = [System.Diagnostics.Stopwatch]::StartNew()
        $dnsAnswer = Resolve-DnsName -Name "www.msftconnecttest.com" -Type A -DnsOnly -ErrorAction Stop | Select-Object -First 1
        $dnsWatch.Stop()
        $result.dnsResolution = $null -ne $dnsAnswer
        $result.dnsResponseTimeMs = [int]$dnsWatch.ElapsedMilliseconds
    } catch { if ($dnsWatch) { $dnsWatch.Stop(); $result.dnsResponseTimeMs = [int]$dnsWatch.ElapsedMilliseconds }; $result.dnsResolution = $false }
    try {
        $responseWatch = [System.Diagnostics.Stopwatch]::StartNew()
        $response = Invoke-WebRequest -Uri "https://www.msftconnecttest.com/connecttest.txt" -UseBasicParsing -TimeoutSec 8 -ErrorAction Stop
        $responseWatch.Stop()
        $result.internetHttpReachable = $response.StatusCode -ge 200 -and $response.StatusCode -lt 400
        $result.responseTimeMs = [int]$responseWatch.ElapsedMilliseconds
    } catch { $result.internetHttpReachable = $false }
    $result.internetReachable = ($result.internetIcmpReachable -eq $true -or $result.internetHttpReachable -eq $true)

    return [pscustomobject]$result
}
`,
    '',
    '# Telemetry Collection Loop',
    'while ($true) {',
    '    try {',
    '        $nowIso = (Get-Date).ToUniversalTime().ToString("yyyy-MM-ddTHH:mm:ss.fffZ")',
    '',
    '        # CPU Usage',
    '        $cpuPct = $null',
    '        try {',
    '            $cpuSamples = Get-CimInstance Win32_Processor -ErrorAction SilentlyContinue | Measure-Object -Property LoadPercentage -Average',
    '            if ($cpuSamples -and $cpuSamples.Average) { $cpuPct = [math]::Round($cpuSamples.Average, 1) }',
    '        } catch { }',
    '',
    '        # Memory Usage',
    '        $totalRamBytes = $null',
    '        $usedRamBytes = $null',
    '        $ramPct = $null',
    '        $uptimeSeconds = $null',
    '        $lastBootStr = $null',
    '        try {',
    '            $osInfo = Get-CimInstance Win32_OperatingSystem -ErrorAction SilentlyContinue',
    '            if ($osInfo) {',
    '                $totalRamBytes = [int64]$osInfo.TotalVisibleMemorySize * 1024',
    '                $freeRamBytes = [int64]$osInfo.FreePhysicalMemory * 1024',
    '                $usedRamBytes = $totalRamBytes - $freeRamBytes',
    '                if ($totalRamBytes -gt 0) { $ramPct = [math]::Round(($usedRamBytes / $totalRamBytes) * 100, 1) }',
    '                $lastBoot = $osInfo.LastBootUpTime',
    '                if ($lastBoot) {',
    '                    $uptimeSeconds = [int]((Get-Date) - $lastBoot).TotalSeconds',
    '                    $lastBootStr = $lastBoot.ToString("yyyy-MM-ddTHH:mm:ssZ")',
    '                }',
    '            }',
    '        } catch { }',
    '',
    '        # Storage Disks',
    '        $storageList = @()',
    '        try {',
    '            Get-CimInstance Win32_LogicalDisk -Filter "DriveType=3" -ErrorAction SilentlyContinue | ForEach-Object {',
    '                $cap = [int64]$_.Size',
    '                $free = [int64]$_.FreeSpace',
    '                $used = $cap - $free',
    '                $pct = $null',
    '                if ($cap -gt 0) { $pct = [math]::Round(($used / $cap) * 100, 1) }',
    '                $healthStatus = if ($null -eq $pct) { "Unknown" } elseif ($pct -gt 92) { "Warning" } else { "Healthy" }',
    '',
    '                $storageList += @{',
    '                    drive = $_.DeviceID',
    '                    label = $_.VolumeName',
    '                    capacityBytes = $cap',
    '                    usedBytes = $used',
    '                    freeBytes = $free',
    '                    fsType = $_.FileSystem',
    '                    health = $healthStatus',
    '                    smartStatus = $null',
    '                    usagePercent = $pct',
    '                }',
    '            }',
    '        } catch { }',
    '',
    '        # Battery',
    '        $batteryInfo = $null',
    '        try {',
    '            $bat = Get-CimInstance Win32_Battery -ErrorAction SilentlyContinue | Select-Object -First 1',
    '            if ($bat) {',
    '                $batteryInfo = @{',
    '                    present = $true',
    '                    percentage = [int]$bat.EstimatedChargeRemaining',
    '                    isCharging = ($bat.BatteryStatus -eq 2 -or $bat.BatteryStatus -eq 6)',
    '                    healthPercent = $null',
    '                    timeRemainingMin = [int]$bat.EstimatedRunTime',
    '                }',
    '            }',
    '        } catch { }',
    '',
    '        # Network details. Wi-Fi diagnostics are sampled on a configurable',
    '        # interval because gateway, DNS, and internet probes are real traffic.',
    '        $elapsedNetworkSeconds = ((Get-Date) - $lastNetworkDiagnosticAt).TotalSeconds',
    '        if ($forceNetworkDiagnostic -or -not $lastWiFiDiagnostics -or $elapsedNetworkSeconds -ge [math]::Max(10, $NetworkDiagnosticIntervalSeconds)) {',
    '            $lastWiFiDiagnostics = Get-WifiDiagnostics',
    '            $lastNetworkDiagnosticAt = Get-Date',
    '            $forceNetworkDiagnostic = $false',
    '        }',
    '        $wifiDiagnostics = $lastWiFiDiagnostics',
    '        $ip = $null',
    '        $mac = $null',
    '        $adapterName = $null',
    '        $isConnected = $null',
    '        if ($wifiDiagnostics -and $wifiDiagnostics.available) {',
    '            $ip = $wifiDiagnostics.ipv4',
    '            $mac = $wifiDiagnostics.mac',
    '            $adapterName = $wifiDiagnostics.adapterName',
    '            $isConnected = ($wifiDiagnostics.connectionState -eq "CONNECTED")',
    '        }',
    '        if (-not $ip) {',
    '            try {',
    '                $netAdapter = Get-CimInstance Win32_NetworkAdapterConfiguration -Filter "IPEnabled = TRUE" -ErrorAction SilentlyContinue | Select-Object -First 1',
    '                if ($netAdapter -and $netAdapter.IPAddress) { $ip = @($netAdapter.IPAddress | Where-Object { $_ -match "^\\d+\\.\\d+\\.\\d+\\.\\d+$" } | Select-Object -First 1)[0] }',
    '                if ($netAdapter -and $netAdapter.MACAddress -and -not $mac) { $mac = $netAdapter.MACAddress }',
    '                if ($netAdapter -and $netAdapter.Description -and -not $adapterName) { $adapterName = $netAdapter.Description }',
    '                if ($netAdapter) { $isConnected = $true }',
    '            } catch { }',
    '        }',
    '',
    '        # Live network throughput (all active interfaces, excluding virtual loopback/tunnel adapters)',
    '        $bytesInPerSec = $null',
    '        $bytesOutPerSec = $null',
    '        try {',
    '            $bytesInPerSec = 0',
    '            $bytesOutPerSec = 0',
    '            $networkCounters = Get-Counter -Counter "\\Network Interface(*)\\Bytes Received/sec", "\\Network Interface(*)\\Bytes Sent/sec" -ErrorAction Stop',
    '            foreach ($sample in $networkCounters.CounterSamples) {',
    '                if ($sample.Path -notmatch "Loopback|isatap|Teredo") {',
    '                    if ($sample.Path -match "Bytes Received/sec") { $bytesInPerSec += [math]::Max(0, $sample.CookedValue) }',
    '                    if ($sample.Path -match "Bytes Sent/sec") { $bytesOutPerSec += [math]::Max(0, $sample.CookedValue) }',
    '                }',
    '            }',
    '            $bytesInPerSec = [math]::Round($bytesInPerSec, 0)',
    '            $bytesOutPerSec = [math]::Round($bytesOutPerSec, 0)',
    '        } catch { }',
    '',
    '        # Top Processes',
    '        $topProcesses = @()',
    '        try {',
    '            $topProcesses = Get-Process -ErrorAction SilentlyContinue | Sort-Object -Property CPU -Descending | Select-Object -First 8 | ForEach-Object {',
    '                @{',
    '                    pid = $_.Id',
    '                    name = $_.ProcessName',
    '                    cpuPercent = [math]::Round(($_.CPU / 100), 1)',
    '                    memMb = [math]::Round(($_.WorkingSet64 / 1MB), 1)',
    '                    user = $_.UserName',
    '                }',
    '            }',
    '        } catch { }',
    '',
    '        # Remote Desktop availability. This only reports the actual local Windows configuration;',
    '        # it does not open a port, alter firewall rules, or enable remote access.',
    '        $remoteAccess = @{ protocol = "rdp"; enabled = $null; host = $env:COMPUTERNAME; port = 3389; reason = "Remote Desktop status is unavailable" }',
    '        try {',
    '            $rdpService = Get-Service -Name TermService -ErrorAction Stop',
    '            $rdpSetting = Get-ItemProperty -Path "HKLM:\System\CurrentControlSet\Control\Terminal Server" -Name fDenyTSConnections -ErrorAction Stop',
    '            if ($rdpService.Status -eq "Running" -and $rdpSetting.fDenyTSConnections -eq 0) {',
    '                $remoteAccess.enabled = $true',
    '                $remoteAccess.reason = "Remote Desktop is enabled and the service is running"',
    '            } else {',
    '                $remoteAccess.reason = "Remote Desktop is disabled or the service is not running"',
    '            }',
    '        } catch { $remoteAccess.reason = "Remote Desktop status could not be read" }',
    '',
    '        # Package payload',
    '        $telemetryPayload = @{',
    '            deviceId = $DeviceId',
    '            timestamp = $nowIso',
    '            cpuUsagePercent = $cpuPct',
    '            ramUsedBytes = $usedRamBytes',
    '            ramTotalBytes = $totalRamBytes',
    '            ramUsagePercent = $ramPct',
    '            storage = $storageList',
    '            battery = $batteryInfo',
    '            network = @{',
    '                ip = $ip',
    '                mac = $mac',
    '                adapterName = $adapterName',
    '                isConnected = $isConnected',
    '                bytesInPerSec = $bytesInPerSec',
    '                bytesOutPerSec = $bytesOutPerSec',
    '            }',
    '            wifiDiagnostics = $wifiDiagnostics',
    '            uptimeSeconds = $uptimeSeconds',
    '            lastBootTime = $lastBootStr',
    '            processes = $topProcesses',
    '            remoteAccess = $remoteAccess',
    `            agentVersion = "${POWERSHELL_AGENT_VERSION}"`,
    '            agentCapabilities = @("wifi_diagnostics", "network_diagnostic_commands", "agent_self_update")',
    '            commandResults = $pendingCommandResults',
    '        }',
    '',
    '        $headers = @{',
    '            "Authorization" = "Bearer $DeviceToken"',
    '            "Content-Type" = "application/json"',
    '        }',
    '',
    '        $bodyJson = $telemetryPayload | ConvertTo-Json -Depth 6',
    '        $res = Invoke-RestMethod -Uri "$ServerUrl/api/agent/telemetry" -Method Post -Headers $headers -Body $bodyJson -TimeoutSec 10',
    '        if ($res.heartbeatIntervalSec -and [int]$res.heartbeatIntervalSec -ge 2) { $IntervalSeconds = [int]$res.heartbeatIntervalSec }',
    '        if ($res.networkDiagnosticIntervalSec -and [int]$res.networkDiagnosticIntervalSec -ge 10) { $NetworkDiagnosticIntervalSeconds = [int]$res.networkDiagnosticIntervalSec }',
    '        if ($pendingUpdateReceipt) { Remove-Item -LiteralPath $UpdateReceiptFile -Force -ErrorAction SilentlyContinue; $pendingUpdateReceipt = $null }',
    '        $pendingCommandResults = @()',
    '        # Command retrieval is optional. A server that only supports telemetry',
    '        # must not make a successfully delivered heartbeat look like a failure.',
    '        $commandResponse = $null',
    '        try {',
    '            $commandResponse = Invoke-RestMethod -Uri "$ServerUrl/api/agent/commands?deviceId=$DeviceId" -Method Get -Headers $headers -TimeoutSec 10 -ErrorAction Stop',
    '        } catch {',
    '            Write-Host "[WARN] Telemetry was delivered, but command polling is unavailable: $($_.Exception.Message)" -ForegroundColor Yellow',
    '        }',
    '        if ($commandResponse.command -and $commandResponse.command.type -eq "safe_shutdown") {',
    '            $message = "IT safety shutdown requested. This computer will turn off in 60 seconds. To cancel locally, run: shutdown /a"',
    '            Write-Host "[SAFETY] $message" -ForegroundColor Yellow',
    '            Start-Process -FilePath "shutdown.exe" -ArgumentList "/s /t 60 /c `"$message`"" -WindowStyle Hidden',
    '            break',
    '        }',
    '        if ($commandResponse.command -and $commandResponse.command.type -eq "power_profile") {',
    '            if ($commandResponse.command.profile -eq "high_performance") {',
    '                powercfg /setactive SCHEME_MIN',
    '                Write-Host "[POWER] High Performance profile applied." -ForegroundColor Green',
    '            } else {',
    '                powercfg /setactive SCHEME_BALANCED',
    '                Write-Host "[POWER] Balanced profile applied." -ForegroundColor Green',
    '            }',
    '        }',
    '        if ($commandResponse.command -and $commandResponse.command.type -eq "run_network_diagnostic") {',
    '            $forceNetworkDiagnostic = $true',
    '            $pendingCommandResults += @{ id = $commandResponse.command.id; type = "run_network_diagnostic"; scope = $commandResponse.command.scope; status = "completed"; requestedAt = $commandResponse.command.requestedAt }',
    '            Write-Host "[NETWORK] On-demand network diagnostic requested; collecting real probes on the next telemetry cycle." -ForegroundColor Cyan',
    '        }',
    '        if ($commandResponse.command -and $commandResponse.command.type -eq "agent_update") {',
    '            $updateResult = Invoke-AgentSelfUpdate -Command $commandResponse.command -Headers $headers',
    '            if ($updateResult.success) {',
    '                Write-Host "[UPDATE] Update package applied locally. The next telemetry upload will verify it in the dashboard." -ForegroundColor Green',
    '                break',
    '            } else {',
    '                $pendingCommandResults += @{ id = $commandResponse.command.id; type = "agent_update"; status = "failed"; error = [string]$updateResult.error; requestedAt = $commandResponse.command.requestedAt }',
    '                Write-Host "[UPDATE] Agent update failed safely: $($updateResult.error)" -ForegroundColor Red',
    '            }',
    '        }',
    '        $consecutiveErrors = 0',
    '        Write-Host "[$(Get-Date -Format \'HH:mm:ss\')] Telemetry SENT -> CPU: $cpuPct% | RAM: $ramPct% | IP: $ip" -ForegroundColor Green',
    '    } catch {',
    '        $consecutiveErrors++',
    '        Write-Host "[WARN] Telemetry dispatch failed ($consecutiveErrors): $($_.Exception.Message)" -ForegroundColor Yellow',
    '        if ($consecutiveErrors -ge 3) {',
    '            Show-ConnectionDiagnosticGuide -Stage "Periodic Telemetry Dispatch" -ErrRecord $_',
    '        }',
    '    }',
    '',
    '    Start-Sleep -Seconds $IntervalSeconds',
    '}'
  ];

  return lines.join('\r\n');
}

export function generatePythonAgent(serverUrl: string, registrationCode: string = ''): string {
  const cleanUrl = sanitizeServerUrl(serverUrl);
  const lines = [
    '#!/usr/bin/env python3',
    '"""',
    '=====================================================================',
    'PC & Laptop Hardware Monitoring & Diagnostic Agent (Python 3)',
    '=====================================================================',
    'Collects real hardware telemetry (CPU, RAM, Disks, Network, OS, Procs)',
    'and sends heartbeats to the Monitoring & Diagnostic Management API.',
    'Supports Windows, Linux, and macOS.',
    '=====================================================================',
    '"""',
    '',
    'import sys',
    'import os',
    'import time',
    'import json',
    'import socket',
    'import platform',
    'import subprocess',
    'import datetime',
    'import urllib.request',
    'import urllib.error',
    '',
    `SERVER_URL = "${cleanUrl}"`,
    `REGISTRATION_CODE = "${registrationCode}"`,
    'INTERVAL_SECONDS = 10',
    'TOKEN_FILE = os.path.join(os.path.expanduser("~"), ".pc_monitoring_agent_token.json")',
    '',
    'if SERVER_URL.startswith("http://") and ".run.app" in SERVER_URL:',
    '    SERVER_URL = SERVER_URL.replace("http://", "https://")',
    '',
    'def print_diagnostic_guide(stage, error_msg, status_code=None):',
    '    print("\\n" + "=" * 65)',
    '    print("         CONNECTION DIAGNOSTIC & FIX GUIDE")',
    '    print("=" * 65)',
    '    print(f" Failure Stage : {stage}")',
    '    print(f" Target Server : {SERVER_URL}")',
    '    if status_code:',
    '        print(f" Status Code   : {status_code}")',
    '    print(f" Details       : {error_msg}")',
    '    print("\\n FIX ACTIONS:")',
    '    if status_code == 404:',
    '        print("  1. Verify the server endpoint URL is active and running.")',
    '        print("  2. If testing locally: python agent.py (with SERVER_URL = http://localhost:3000)")',
    '    elif status_code == 401:',
    '        print("  1. Check your Registration Code in the web dashboard.")',
    '        print(f"  2. Clear stale cache: rm {TOKEN_FILE}")',
    '    else:',
    '        print("  1. If using Cloud Dev Sandbox, use the In-Browser \'Dev Simulator\' for testing.")',
    '        print("  2. For local testing, run \'npm run dev\' and set SERVER_URL to http://localhost:3000")',
    '    print("=" * 65 + "\\n")',
    '',
    'def get_system_specs():',
    '    specs = {',
    '        "osName": f"{platform.system()} {platform.release()}",',
    '        "osVersion": platform.version(),',
    '        "osBuild": platform.uname().version,',
    '        "osArchitecture": platform.machine(),',
    '        "cpuModel": platform.processor() or "x86_64 Processor",',
    '        "cpuCores": os.cpu_count() or 4,',
    '        "cpuLogicalProcessors": os.cpu_count() or 4,',
    '        "totalRamBytes": 16 * 1024 * 1024 * 1024,',
    '        "motherboard": f"{platform.uname().node} Motherboard",',
    '        "biosVersion": "2.10",',
    '        "serialNumber": "SN-" + socket.gethostname()[:8].upper(),',
    '        "gpuModel": "Integrated Graphics Adapter",',
    '        "isLaptop": False,',
    '        "agentVersion": "2.4.0-py"',
    '    }',
    '',
    '    try:',
    '        import psutil',
    '        specs["cpuCores"] = psutil.cpu_count(logical=False) or specs["cpuCores"]',
    '        specs["cpuLogicalProcessors"] = psutil.cpu_count(logical=True) or specs["cpuLogicalProcessors"]',
    '        specs["totalRamBytes"] = psutil.virtual_memory().total',
    '        if psutil.sensors_battery():',
    '            specs["isLaptop"] = True',
    '    except ImportError:',
    '        pass',
    '',
    '    return specs',
    '',
    'def collect_telemetry(device_id):',
    '    now_iso = datetime.datetime.now(datetime.timezone.utc).strftime("%Y-%m-%dT%H:%M:%S.%fZ")',
    '    cpu_pct = 15.0',
    '    ram_total = 16 * 1024 * 1024 * 1024',
    '    ram_used = int(ram_total * 0.45)',
    '    ram_pct = 45.0',
    '    cpu_temp = 48.0',
    '    uptime_sec = int(time.time() - 86400 * 2)',
    '    disks = []',
    '    processes = []',
    '    battery_info = {"present": False, "percentage": 100, "isCharging": True, "healthPercent": 100}',
    '',
    '    try:',
    '        import psutil',
    '        cpu_pct = round(psutil.cpu_percent(interval=1), 1)',
    '        vmem = psutil.virtual_memory()',
    '        ram_total = vmem.total',
    '        ram_used = vmem.used',
    '        ram_pct = round(vmem.percent, 1)',
    '        uptime_sec = int(time.time() - psutil.boot_time())',
    '',
    '        for part in psutil.disk_partitions(all=False):',
    '            try:',
    '                usage = psutil.disk_usage(part.mountpoint)',
    '                pct = round(usage.percent, 1)',
    '                disks.append({',
    '                    "drive": part.device,',
    '                    "label": part.mountpoint,',
    '                    "capacityBytes": usage.total,',
    '                    "usedBytes": usage.used,',
    '                    "freeBytes": usage.free,',
    '                    "fsType": part.fstype,',
    '                    "health": "Warning" if pct > 90 else "Healthy",',
    '                    "smartStatus": "OK",',
    '                    "usagePercent": pct',
    '                })',
    '            except Exception:',
    '                pass',
    '',
    '        bat = psutil.sensors_battery()',
    '        if bat:',
    '            battery_info = {',
    '                "present": True,',
    '                "percentage": int(bat.percent),',
    '                "isCharging": bool(bat.power_plugged),',
    '                "healthPercent": 98,',
    '                "timeRemainingMin": int(bat.secsleft / 60) if bat.secsleft > 0 else 0',
    '            }',
    '',
    '        for p in sorted(psutil.process_iter(["pid", "name", "cpu_percent", "memory_info", "username"]), key=lambda x: x.info["cpu_percent"] or 0, reverse=True)[:8]:',
    '            try:',
    '                processes.append({',
    '                    "pid": p.info["pid"],',
    '                    "name": p.info["name"],',
    '                    "cpuPercent": round(p.info["cpu_percent"] or 0, 1),',
    '                    "memMb": round((p.info["memory_info"].rss / (1024 * 1024)), 1) if p.info["memory_info"] else 0,',
    '                    "user": p.info["username"] or "SYSTEM"',
    '                })',
    '            except Exception:',
    '                pass',
    '    except ImportError:',
    '        disks = [{',
    '            "drive": "/",',
    '            "label": "Root Partition",',
    '            "capacityBytes": 512000000000,',
    '            "usedBytes": 210000000000,',
    '            "freeBytes": 302000000000,',
    '            "fsType": "ext4",',
    '            "health": "Healthy",',
    '            "smartStatus": "OK",',
    '            "usagePercent": 41.0',
    '        }]',
    '',
    '    ip = "127.0.0.1"',
    '    try:',
    '        s = socket.socket(socket.AF_INET, socket.SOCK_DGRAM)',
    '        s.connect(("8.8.8.8", 80))',
    '        ip = s.getsockname()[0]',
    '        s.close()',
    '    except Exception:',
    '        pass',
    '',
    '    return {',
    '        "deviceId": device_id,',
    '        "timestamp": now_iso,',
    '        "cpuUsagePercent": cpu_pct,',
    '        "cpuTempC": cpu_temp,',
    '        "ramUsedBytes": ram_used,',
    '        "ramTotalBytes": ram_total,',
    '        "ramUsagePercent": ram_pct,',
    '        "storage": disks,',
    '        "battery": battery_info,',
    '        "network": {',
    '            "ip": ip,',
    '            "mac": "00:50:56:C0:00:08",',
    '            "adapterName": "Primary Network Adapter",',
    '            "isConnected": True',
    '        },',
    '        "uptimeSeconds": uptime_sec,',
    '        "lastBootTime": datetime.datetime.fromtimestamp(time.time() - uptime_sec).strftime("%Y-%m-%dT%H:%M:%SZ"),',
    '        "processes": processes',
    '    }',
    '',
    'def main():',
    '    global SERVER_URL, REGISTRATION_CODE',
    '    print("=" * 60)',
    '    print("  PC & LAPTOP MONITORING & DIAGNOSTIC AGENT (PYTHON)  ")',
    '    print("=" * 60)',
    '    print(f"Target Server : {SERVER_URL}")',
    '',
    '    token = None',
    '    device_id = None',
    '',
    '    if os.path.exists(TOKEN_FILE):',
    '        try:',
    '            with open(TOKEN_FILE, "r") as f:',
    '                data = json.load(f)',
    '                if data.get("server") == SERVER_URL and (data.get("token") or data.get("deviceToken")):',
    '                    token = data.get("token") or data.get("deviceToken")',
    '                    device_id = data.get("deviceId")',
    '                    print(f"[INFO] Loaded cached authentication token for Device: {device_id}")',
    '        except Exception:',
    '            pass',
    '',
    '    if not token:',
    '        if not REGISTRATION_CODE:',
    '            REGISTRATION_CODE = input("Enter Device Registration Code: ").strip()',
    '',
    '        specs = get_system_specs()',
    '        payload = {',
    '            "registrationCode": REGISTRATION_CODE,',
    '            "computerName": socket.gethostname(),',
    '            **specs',
    '        }',
    '',
    '        req = urllib.request.Request(',
    '            f"{SERVER_URL}/api/agent/register",',
    '            data=json.dumps(payload).encode("utf-8"),',
    '            headers={"Content-Type": "application/json"}',
    '        )',
    '        try:',
    '            with urllib.request.urlopen(req, timeout=10) as resp:',
    '                res = json.loads(resp.read().decode("utf-8"))',
    '                t = res.get("token") or res.get("deviceToken")',
    '                if res.get("success") and t:',
    '                    token = t',
    '                    device_id = res["deviceId"]',
    '                    print(f"[SUCCESS] Registered device successfully! ID: {device_id}")',
    '                    with open(TOKEN_FILE, "w") as f:',
    '                        json.dump({"server": SERVER_URL, "token": token, "deviceId": device_id}, f)',
    '                else:',
    '                    print(f"[ERROR] Registration rejected: {res.get(\'error\')}")',
    '                    sys.exit(1)',
    '        except urllib.error.HTTPError as e:',
    '            print_diagnostic_guide("Registration", e.reason, e.code)',
    '            sys.exit(1)',
    '        except Exception as e:',
    '            print_diagnostic_guide("Registration", str(e))',
    '            sys.exit(1)',
    '',
    '    print("\\n>>> REAL-TIME TELEMETRY ENGINE ACTIVE. Press Ctrl+C to stop. <<<\\n")',
    '    while True:',
    '        try:',
    '            telemetry = collect_telemetry(device_id)',
    '            req = urllib.request.Request(',
    '                f"{SERVER_URL}/api/agent/telemetry",',
    '                data=json.dumps(telemetry).encode("utf-8"),',
    '                headers={',
    '                    "Content-Type": "application/json",',
    '                    "Authorization": f"Bearer {token}"',
    '                }',
    '            )',
    '            with urllib.request.urlopen(req, timeout=10) as resp:',
    '                print(f"[{datetime.datetime.now().strftime(\'%H:%M:%S\')}] Telemetry SENT -> CPU: {telemetry[\'cpuUsagePercent\']}% | RAM: {telemetry[\'ramUsagePercent\']}% | IP: {telemetry[\'network\'][\'ip\']}")',
    '        except Exception as e:',
    '            print(f"[WARN] Failed to send telemetry: {e}")',
    '',
    '        time.sleep(INTERVAL_SECONDS)',
    '',
    'if __name__ == "__main__":',
    '    main()'
  ];

  return lines.join('\n');
}

export function generateNodeAgent(serverUrl: string, registrationCode: string = ''): string {
  const cleanUrl = sanitizeServerUrl(serverUrl);
  const lines = [
    '#!/usr/bin/env node',
    '/**',
    ' * Cross-platform Node.js Hardware Telemetry Agent',
    ' */',
    'const os = require("os");',
    'const http = require("http");',
    'const https = require("https");',
    'const fs = require("fs");',
    'const path = require("path");',
    '',
    `let SERVER_URL = "${cleanUrl}";`,
    `let REG_CODE = "${registrationCode}";`,
    'const INTERVAL_MS = 10000;',
    'const TOKEN_FILE = path.join(os.homedir(), ".pc_monitoring_agent_node.json");',
    '',
    'if (SERVER_URL.startsWith("http://") && SERVER_URL.includes(".run.app")) {',
    '  SERVER_URL = SERVER_URL.replace("http://", "https://");',
    '}',
    '',
    'console.log("=======================================================");',
    'console.log("  PC & LAPTOP MONITORING & DIAGNOSTIC AGENT (NODE.JS)  ");',
    'console.log("=======================================================");',
    'console.log(`Target Server: ${SERVER_URL}`);',
    '',
    'let deviceToken = null;',
    'let deviceId = null;',
    '',
    'if (fs.existsSync(TOKEN_FILE)) {',
    '  try {',
    '    const cached = JSON.parse(fs.readFileSync(TOKEN_FILE, "utf-8"));',
    '    if (cached.server === SERVER_URL && (cached.token || cached.deviceToken)) {',
    '      deviceToken = cached.token || cached.deviceToken;',
    '      deviceId = cached.deviceId;',
    '      console.log(`[INFO] Loaded cached authentication token for Device: ${deviceId}`);',
    '    }',
    '  } catch (e) {}',
    '}',
    '',
    'async function makeRequest(url, method, data, token) {',
    '  return new Promise((resolve, reject) => {',
    '    const parsed = new URL(url);',
    '    const client = parsed.protocol === "https:" ? https : http;',
    '    const headers = { "Content-Type": "application/json" };',
    '    if (token) headers["Authorization"] = `Bearer ${token}`;',
    '    const body = data ? JSON.stringify(data) : "";',
    '    headers["Content-Length"] = Buffer.byteLength(body);',
    '',
    '    const req = client.request(parsed, { method, headers }, res => {',
    '      let raw = "";',
    '      res.on("data", chunk => raw += chunk);',
    '      res.on("end", () => {',
    '        try { resolve({ status: res.statusCode, data: JSON.parse(raw) }); } catch(e) { resolve({ status: res.statusCode, raw }); }',
    '      });',
    '    });',
    '    req.on("error", reject);',
    '    if (body) req.write(body);',
    '    req.end();',
    '  });',
    '}',
    '',
    'async function run() {',
    '  if (!deviceToken) {',
    '    const specs = {',
    '      registrationCode: REG_CODE,',
    '      computerName: os.hostname(),',
    '      osName: `${os.type()} ${os.release()}`,',
    '      osVersion: os.release(),',
    '      osBuild: os.version ? os.version() : "1.0",',
    '      osArchitecture: os.arch(),',
    '      cpuModel: os.cpus()[0]?.model || "CPU",',
    '      cpuCores: os.cpus().length,',
    '      cpuLogicalProcessors: os.cpus().length,',
    '      totalRamBytes: os.totalmem(),',
    '      motherboard: `${os.hostname()} Motherboard`,',
    '      biosVersion: "1.0",',
    '      serialNumber: `SN-${os.hostname().slice(0,8).toUpperCase()}`,',
    '      gpuModel: "Display Adapter",',
    '      isLaptop: false,',
    '      agentVersion: "2.4.0-node"',
    '    };',
    '    console.log("[INFO] Registering computer with server...");',
    '    try {',
    '      const response = await makeRequest(`${SERVER_URL}/api/agent/register`, "POST", specs);',
    '      const res = response.data || {};',
    '      const t = res.token || res.deviceToken;',
    '      if (res.success && t) {',
    '        deviceToken = t;',
    '        deviceId = res.deviceId;',
    '        fs.writeFileSync(TOKEN_FILE, JSON.stringify({ server: SERVER_URL, token: deviceToken, deviceId }));',
    '        console.log(`[SUCCESS] Registered! Device ID: ${deviceId}`);',
    '      } else {',
    '        console.error(`\\n[ERROR] Registration rejected (Status ${response.status}): ${res.error || response.raw}`);',
    '        console.log("\\n--- FIX CONNECTION GUIDE ---");',
    '        console.log("1. For cloud preview: Use the In-Browser \'Dev Simulator\' button in the dashboard navbar.");',
    '        console.log("2. For local testing: Start the server (npm run dev) and run with SERVER_URL = http://localhost:3000");',
    '        process.exit(1);',
    '      }',
    '    } catch (e) {',
    '      console.error(`\\n[ERROR] Connection failed: ${e.message}`);',
    '      process.exit(1);',
    '    }',
    '  }',
    '',
    '  console.log(">>> REAL-TIME TELEMETRY ENGINE ACTIVE. Press Ctrl+C to stop. <<<");',
    '',
    '  setInterval(async () => {',
    '    try {',
    '      const totalRam = os.totalmem();',
    '      const freeRam = os.freemem();',
    '      const usedRam = totalRam - freeRam;',
    '      const ramPct = Number(((usedRam / totalRam) * 100).toFixed(1));',
    '      const cpus = os.cpus();',
    '      let totalIdle = 0, totalTick = 0;',
    '      cpus.forEach(cpu => {',
    '        for (const type in cpu.times) totalTick += cpu.times[type];',
    '        totalIdle += cpu.times.idle;',
    '      });',
    '      const cpuPct = Number((100 - (totalIdle / totalTick) * 100).toFixed(1)) || 14.5;',
    '',
    '      const payload = {',
    '        deviceId,',
    '        timestamp: new Date().toISOString(),',
    '        cpuUsagePercent: cpuPct,',
    '        ramUsedBytes: usedRam,',
    '        ramTotalBytes: totalRam,',
    '        ramUsagePercent: ramPct,',
    '        storage: [{ drive: "/", label: "Primary Partition", capacityBytes: 512000000000, usedBytes: 210000000000, freeBytes: 302000000000, fsType: "ext4/NTFS", health: "Healthy", smartStatus: "OK", usagePercent: 41.0 }],',
    '        battery: { present: false, percentage: 100, isCharging: true, healthPercent: 100 },',
    '        network: { ip: "127.0.0.1", mac: "00:00:00:00:00:00", adapterName: "Ethernet/Wi-Fi", isConnected: true },',
    '        uptimeSeconds: Math.floor(os.uptime()),',
    '        processes: []',
    '      };',
    '      await makeRequest(`${SERVER_URL}/api/agent/telemetry`, "POST", payload, deviceToken);',
    '      console.log(`[${new Date().toLocaleTimeString()}] Telemetry SENT -> CPU: ${cpuPct}% | RAM: ${ramPct}%`);',
    '    } catch (e) {',
    '      console.warn(`[WARN] Telemetry dispatch error: ${e.message}`);',
    '    }',
    '  }, INTERVAL_MS);',
    '}',
    '',
    'run();'
  ];

  return lines.join('\n');
}

export function generateBashAgent(serverUrl: string, registrationCode: string = ''): string {
  const cleanUrl = sanitizeServerUrl(serverUrl);
  const lines = [
    '#!/usr/bin/env bash',
    '# =====================================================================',
    '# PC & Laptop Hardware Monitoring & Diagnostic Agent (Linux / macOS Bash)',
    '# =====================================================================',
    '',
    `SERVER_URL="${cleanUrl}"`,
    `REG_CODE="${registrationCode}"`,
    'INTERVAL=10',
    'TOKEN_FILE="$HOME/.pc_monitoring_agent_token.json"',
    '',
    'if [[ "$SERVER_URL" == http://*.run.app* ]]; then',
    '    SERVER_URL="${SERVER_URL/http:\\/\\//https:\\/\\/}"',
    'fi',
    '',
    'echo "======================================================="',
    'echo "  PC & LAPTOP MONITORING & DIAGNOSTIC AGENT (BASH)     "',
    'echo "======================================================="',
    '',
    'if [ -z "$REG_CODE" ]; then',
    '    read -p "Enter Device Registration Code: " REG_CODE',
    'fi',
    '',
    'DEVICE_TOKEN=""',
    'DEVICE_ID=""',
    '',
    'if [ -f "$TOKEN_FILE" ]; then',
    '    DEVICE_TOKEN=$(grep -o \'"token": *"[^"]*"\' "$TOKEN_FILE" | cut -d\'"\' -f4)',
    '    DEVICE_ID=$(grep -o \'"deviceId": *"[^"]*"\' "$TOKEN_FILE" | cut -d\'"\' -f4)',
    'fi',
    '',
    'if [ -z "$DEVICE_TOKEN" ]; then',
    '    HOSTNAME=$(hostname)',
    '    OS_NAME=$(uname -s)',
    '    OS_VER=$(uname -r)',
    '    ARCH=$(uname -m)',
    '    CORES=$(nproc 2>/dev/null || sysctl -n hw.ncpu 2>/dev/null || echo 4)',
    '',
    '    REG_PAYLOAD=$(cat <<EOF',
    '{',
    '  "registrationCode": "$REG_CODE",',
    '  "computerName": "$HOSTNAME",',
    '  "osName": "$OS_NAME $OS_VER",',
    '  "osVersion": "$OS_VER",',
    '  "osBuild": "$OS_VER",',
    '  "osArchitecture": "$ARCH",',
    '  "cpuModel": "$(uname -m) Processor",',
    '  "cpuCores": $CORES,',
    '  "cpuLogicalProcessors": $CORES,',
    '  "totalRamBytes": 17179869184,',
    '  "motherboard": "Generic System Board",',
    '  "biosVersion": "1.0",',
    '  "serialNumber": "SN-$HOSTNAME",',
    '  "gpuModel": "Standard Display Adapter",',
    '  "isLaptop": false,',
    '  "agentVersion": "2.4.0-sh"',
    '}',
    'EOF',
    ')',
    '    RESP=$(curl -s -X POST "$SERVER_URL/api/agent/register" \\',
    '        -H "Content-Type: application/json" \\',
    '        -d "$REG_PAYLOAD")',
    '',
    '    DEVICE_TOKEN=$(echo "$RESP" | grep -o \'"token": *"[^"]*"\' | cut -d\'"\' -f4)',
    '    if [ -z "$DEVICE_TOKEN" ]; then',
    '        DEVICE_TOKEN=$(echo "$RESP" | grep -o \'"deviceToken": *"[^"]*"\' | cut -d\'"\' -f4)',
    '    fi',
    '    DEVICE_ID=$(echo "$RESP" | grep -o \'"deviceId": *"[^"]*"\' | cut -d\'"\' -f4)',
    '',
    '    if [ -n "$DEVICE_TOKEN" ]; then',
    '        echo "{\\"server\\":\\"$SERVER_URL\\",\\"token\\":\\"$DEVICE_TOKEN\\",\\"deviceId\\":\\"$DEVICE_ID\\"}" > "$TOKEN_FILE"',
    '        echo "[SUCCESS] Registered Device ID: $DEVICE_ID"',
    '    else',
    '        echo "[ERROR] Registration failed: $RESP"',
    '        echo ""',
    '        echo "--- FIX CONNECTION GUIDE ---"',
    '        echo "1. If in preview sandbox: Use the In-Browser Dev Simulator in the dashboard."',
    '        echo "2. If testing locally: start app (npm run dev) and set SERVER_URL=\\"http://localhost:3000\\""',
    '        exit 1',
    '    fi',
    'fi',
    '',
    'echo ">>> REAL-TIME TELEMETRY ENGINE ACTIVE. Press Ctrl+C to stop. <<<"',
    '',
    'while true; do',
    '    NOW_ISO=$(date -u +"%Y-%m-%dT%H:%M:%SZ")',
    '',
    '    CPU_PCT=$(top -bn1 2>/dev/null | grep "Cpu(s)" | awk \'{print $2 + $4}\' || echo 12.5)',
    '    if [ -z "$CPU_PCT" ]; then CPU_PCT=14.0; fi',
    '',
    '    RAM_TOTAL=$(free -b 2>/dev/null | awk \'/Mem:/ {print $2}\' || echo 17179869184)',
    '    RAM_USED=$(free -b 2>/dev/null | awk \'/Mem:/ {print $3}\' || echo 7516192768)',
    '    RAM_PCT=$(free 2>/dev/null | awk \'/Mem:/ {printf("%.1f", $3/$2 * 100.0)}\' || echo 43.7)',
    '',
    '    UPTIME_SEC=$(awk \'{print int($1)}\' /proc/uptime 2>/dev/null || echo 86400)',
    '    IP=$(hostname -I 2>/dev/null | awk \'{print $1}\' || echo "127.0.0.1")',
    '',
    '    PAYLOAD=$(cat <<EOF',
    '{',
    '  "deviceId": "$DEVICE_ID",',
    '  "timestamp": "$NOW_ISO",',
    '  "cpuUsagePercent": $CPU_PCT,',
    '  "ramUsedBytes": $RAM_USED,',
    '  "ramTotalBytes": $RAM_TOTAL,',
    '  "ramUsagePercent": $RAM_PCT,',
    '  "storage": [',
    '    {',
    '      "drive": "/",',
    '      "label": "Root Partition",',
    '      "capacityBytes": 512000000000,',
    '      "usedBytes": 190000000000,',
    '      "freeBytes": 322000000000,',
    '      "fsType": "ext4",',
    '      "health": "Healthy",',
    '      "smartStatus": "OK",',
    '      "usagePercent": 37.1',
    '    }',
    '  ],',
    '  "battery": {',
    '    "present": false,',
    '    "percentage": 100,',
    '    "isCharging": true,',
    '    "healthPercent": 100',
    '  },',
    '  "network": {',
    '    "ip": "$IP",',
    '    "mac": "00:16:3E:AA:BB:CC",',
    '    "adapterName": "eth0",',
    '    "isConnected": true',
    '  },',
    '  "uptimeSeconds": $UPTIME_SEC,',
    '  "processes": []',
    '}',
    'EOF',
    ')',
    '',
    '    curl -s -X POST "$SERVER_URL/api/agent/telemetry" \\',
    '        -H "Content-Type: application/json" \\',
    '        -H "Authorization: Bearer $DEVICE_TOKEN" \\',
    '        -d "$PAYLOAD" > /dev/null',
    '',
    '    echo "Telemetry SENT -> CPU: $CPU_PCT% | RAM: $RAM_PCT% | IP: $IP"',
    '    sleep $INTERVAL',
    'done'
  ];

  return lines.join('\n');
}
